### ISSUE TITLE
BUG: animations colors/size get wrong n_times if x,y,z are unidimensional

### ISSUE THREAD

**Issue by kingjr** [maartenbreddels/ipyvolume#100]
I think there may be a bug on the animation when we only want to animation colors or size.

indeed, if the xyz variables are unidimensional, then the length of times is set to the length of x, as opposed to the length of the colors.

```python
import ipyvolume as p3
import numpy as np
n_points = 20
n_times = 10
x = np.linspace(0, 1, n_points)
y = np.cos(x)
z = np.sin(x)
colors = np.random.randn(n_times, n_points, 3)
p3.figure()
s = p3.scatter(x, y, z, color=colors)
p3.animation_control(s, interval=200)  # animation last for n_points
p3.show()
```
whereas if I duplicate `z` n_times, then it gets the timing right.
```python
s = p3.scatter(x, y, np.array([z for _ in range(n_times)]), color=colors)
p3.animation_control(s, interval=200)  # animation last for n_times
p3.show()
```

But perhaps this is on purpose?

**Comment by maartenbreddels** [comment]
Never expected to reach issue #100 when I started this project! Thanks for the report, and I hope this fixes it for you. Please reopen if it does not.
Cheers!
