### ISSUE TITLE
BUG: memory leak in 3D viz

### ISSUE THREAD

**Issue by kingjr** [maartenbreddels/ipyvolume#101]
There is a memory leak in the animation: the more we play it, the more RAM is taken. The RAM can only be cleaned once we shutdown the notebook. 

```python
fig = p3.figure(width=500, height=500)
brain = p3.plot_trisurf(rr[:, 0], rr[:, 1], rr[:, 2], triangles=tris, color=brain_colors)
p3.squarelim()
p3.animation_control(brain, interval=1)
p3.show()
```

An example script, using data from [MNE](http://github.com/mne-tools/mne-python):
https://gist.github.com/kingjr/cdadefbb5f522ab7450ead746dc0a5b2

![memoryt_leak](https://user-images.githubusercontent.com/4881164/35048007-c2e65e90-fb69-11e7-9340-87410ae6d42b.gif)

(PS: sorry for opening so many issues..)

**Comment by pckroon** [comment]
Referencing #92

**Comment by maartenbreddels** [comment]
Hi Jean-Rémi & Peter,
thanks for the reports! Will take a look at this as soon as I can!

**Comment by kingjr** [comment]
@pckroon : is the memory leak you encountered due to loop playing or to the inability to remove objects form the RAM? If the former, we can indeed close this issue.

**Comment by pckroon** [comment]
@kingjr I'm not sure those are different things. The loop playing means I make a lot of surfaces (same as `animation_control` does for you), and somehow the ones that you no longer see need to be cleaned up. `animation_control` does that behind the scenes somehow.
The only difference between our issues is that I do more things by hand/explicitely.

**Comment by kingjr** [comment]
Ok, I'll keep the issue open until we are sure that these tap onto the same bug.

**Comment by maartenbreddels** [comment]
I can confirm that the Mesh is indeed causing a memory leak. It seems something is keeping a reference to the geometry. Working on it...

**Comment by maartenbreddels** [comment]
Please try if the current masters fixes it. Here is does wonders :)

**Comment by kingjr** [comment]
Thanks, no more leak!

**Comment by pckroon** [comment]
58c30ed doesn't seem to fix it for me, although it did help. :(
My code can be found in #92.

Chromium
Version 63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

If you need any other information, ask!
