### ISSUE TITLE
Improvement: Current Figure Handling

### ISSUE THREAD

**Issue by TimoFriedri** [maartenbreddels/ipyvolume#105]
Hi,

I was struggeling with the way figure handling is implemented. 

This does not work in Ipyvolume but many people are used to do it like this from e.g. matlab.
```
f1 = ipv.figure()
f2 = ipv.figure()
ipv.figure(f1) # make f1 the current figure which is then used e.g. with ipv.movie
```

To make it work you have to do:
```
f1 = ipv.figure(key='f1')
f2 = ipv.figure(key='f2')
ipv.figure('f1') # make f1 the current figure which is then used e.g. with ipv.movie
```
If you know it is done like this, you will understand the documentation. But it took me ages to figure this out. I had to look at the source code in pylab.py. Maybe I am just biased by my Matlab past.

I could imagine to pass a Figure Object to ipv.figure(), then figure() notices the type and searches for that figure in ipv.current.figures.values.
So both usages would work.

Thanks

Bye

PS: Very nice library

**Comment by maartenbreddels** [comment]
Hi Timo,

thanks, and excellent idea, that indeed is expected behaviour. Do you want to try to make a PR for that? I can help if you want.

cheers,

Maarten

**Comment by TimoFriedri** [comment]
Hi Maarten,

I already thought about it. It is right now just limited by free time on my side.
I'll send an PR the next days.

Greets
