### ISSUE TITLE
Stereoscopic side-by-side plots?

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#108]
Again, awesome project!! Any plans to add (or call for) stereoscopic side-by-side plots?

**Comment by maartenbreddels** [comment]
Thanks, try clicking the eye icon in the toolbar, Google cardboard
recommended :)

(from mobile phone)

**Comment by deeplook** [comment]
Hell, yeah, it works! Even without a cardboard! I'm intrigued! 🤓

**Comment by maartenbreddels** [comment]
👍

**Comment by deeplook** [comment]
Have played a bit more with it, and wonder if the spacing between the left and right sides (and any horizontal centering) can be controlled? I see quite a small distance between left/right image resulting in a significant overlap when trying to zoom and find the sweet spot for the effect to occur.

**Comment by maartenbreddels** [comment]
yes, see https://github.com/maartenbreddels/ipyvolume/issues/24
