### ISSUE TITLE
Select Mode in Plot not working

### ISSUE THREAD

**Issue by TimoFriedri** [maartenbreddels/ipyvolume#120]
How is the Select Mode (ctrl pressed) supposed to work. 
I can't select anything in a plot. Should I be able to?
I am pressing the ctrl key and click with my mousepointer on a glyph, but nothing happens.

BTW:
```
s = ipv.scatter(..., selection=[range(100)])
```
does not work for me
```
s.selected = [range(100)]
```
but this does

**Comment by maartenbreddels** [comment]
Hi Timo,

It's still early days for selections, so bear with me:
 * ctrl-drag should show you a lasso tool (i just checked, it seems broken actually, I'll check tomorrow!)
 * ctrl-r should go to rectangle mode
 * ctrl-c should go to circle mode
 * ctrl-l should go to lasso mode
(may be subject to change, input is welcome!)

It is not yet possible to pick single items, although I think that should be possible, although I'm not sure that should translate into a selection (say `s.selected == [100]`), or if the Scatter object should have a new trait, `scatter.picked_index` (and possibly `scatter.hovered_index` ?).

cheers,

Maarten

**Comment by TimoFriedri** [comment]
Hi Maarten,

maybe you should reconsider these keyboard shortcuts. 
I am using Ubuntu/XFCE and Chromium and these shortcuts are used for different stuff, like refresh (ctrl+r).
Basically I cannot use any of these unfortunately.

I would suggest removing this ctrl+ stuff an add a designated little button in the toolbar for each mode. I suppose this is in the Java Script Code of the Widget, I might take a look in the code, but I am no Java Script developer at all.

I would go for s.selected = [100] and maybe hovered as extra. I don't see the reason to add picked_index.

Anyway, thanks again so far.

Regards,

Timo

**Comment by maartenbreddels** [comment]
Hi Timo,

thanks for that, I'm on OSX, but indeed, that would refresh on Windows and Linux (although the default might be prevented, you don't accidentally want to refresh). Buttons in the toolbar are indeed something I plan to do, the only issue now is I'm using fontawesome, which does not have icons for this, so I'd need to find some with a CC0 license orso. 
Btw, i just looked at the code, and you don't need to have ctrl pressed, make sure the div where the canvas is in is selected (should have blue edge around if). 
From code, you can do:
```python
fig = ipv.gcf()
fig.selector = 'rectangle' # or circle/lass
```

Thanks for you input, cheers,

Maarten

**Comment by TimoFriedri** [comment]
HI Maarten,

I'm sorry, but I can't make it work on my machine. I installed the up to date github master and used your code above, but then I can still just rotate the plot.
I added ``` f.camera_control = 'disabled'``` inspired by the js code of widget.js
But this did not help me.

So far for an update, I continue trying to make it work.

Timo

**Comment by maartenbreddels** [comment]
Did you update just a while ago? I pushed a strange fix for a performance issue/bug with Chrome 65 just 3 hours ago. Also, if you press ctrl you should see one of the icons in the toolbar change (the one with the pencil), do you see that?

**Comment by TimoFriedri** [comment]
I pulled from your master just 30min ago. I can see the icon change while pressing ctrl, but can't select anything.

**Comment by maartenbreddels** [comment]
Do you see the lasso?
If so great, it should be working, but to really select objects it needs something extra:
```python
ipv.selector_default()
```
This implements a basic selection mechanism for scatter plots (it doesn't do anything for volumes or meshes yet)

**Comment by TimoFriedri** [comment]
What comes into my mind, you have probably changed the nb extension for ipyvolume. How do I update that from the code within my github clone? I am probably using the one installed during my last 
```conda install ...```

**Comment by maartenbreddels** [comment]
Indeed!
Ok, make sure you have a modern nodejs installed:
```
conda install -c conda-forge nodejs
```
Then do (in the repo root):
```
pip install .
```

**Comment by TimoFriedri** [comment]
Awesome.

I had some troubles with conda install, pip install -e, but now the lasso tool works after calling ```pv.selector_default()```
I will try it out tomorrow and give some feedback.
Thanks


(For anyone to come by: check conda.pth and easy-install.pth in case of troubles with pip install -e and conda)
