### ISSUE TITLE
[Feature Request] Point selection in scatterplot

### ISSUE THREAD

**Issue by epifanio** [maartenbreddels/ipyvolume#124]
Hi, 
I was wondering if it is possible or it is planned in the `ipyvolume` development roadmap, the ability to select points from an `ipyvolume.pyplot.scatter` plot. 
For my use case I would use such a feature to clean noisy raw sonar data. Is this something of interest to the broad community of `ipyvolume` users?

**Comment by maartenbreddels** [comment]
It is implemented (not released yet) on the Python side for now:
```python
ipv.selector_default() # this will listen to selection events and set scatter.selected
```
   * use ctrl+dragging to select points.
   * r goes to rectangle mode
   * c goes to circle mode
   * l goes to lasso mode

Feedback and help welcome. What is missing is indicators/icons/buttons to change the select mode. And I'd love to see a screenshot or screencapture of what you are doing with this!

**Comment by nanodust** [comment]
oh this is fantastic - i was trying to do exactly this (plot WiFi time/rssi/macaddr) and filter out devices interactively. 
shall pull down latest and give it a shot. ! 
here's a screenshot of current plot. 
![screen shot 2018-03-28 at 6 06 17 pm](https://user-images.githubusercontent.com/65142/38060973-ce402a48-32b2-11e8-9010-85367715d36a.png)

btw, i stumbled into ipv when matplotlib.pyplot.figure().gca(projection='3d') works, but just is too slow to be interactive. Very nice work with the library !

**Comment by maartenbreddels** [comment]
Great, thanks for sharing it!
There seems to be a camera issue in master, hope to fix that soon.
