### ISSUE TITLE
Failed to display Jupyter Widget of type VBox

### ISSUE THREAD

**Issue by Lukasfuh** [maartenbreddels/ipyvolume#126]
Hi All,

When Trying to use ipyvolume with juptyter notebook I always get the error message : 

Failed to display Jupyter Widget of type VBox.
If you're reading this message in the Jupyter Notebook or JupyterLab Notebook, it may mean that the widgets JavaScript is still loading. If this message persists, it likely means that the widgets JavaScript library is either not installed or not enabled. See the Jupyter Widgets Documentation for setup instructions. 
If you're reading this message in another frontend (for example, a static rendering on GitHub or NBViewer), it may mean that your frontend doesn't currently support widgets.

However when running all the instructions in the Jupyter Widgets Documentation, the error still occurs. Did anynone have a similar problem or does know how to solve this? Would be happy for any suggestions. Thanks in advance.

**Comment by maartenbreddels** [comment]
Hi, did you solve the issue?
