### ISSUE TITLE
Error displaying widget - jupyterlab

### ISSUE THREAD

**Issue by PhilippBartel** [maartenbreddels/ipyvolume#127]
Running latest conda, ipyvolume and jupyterlab, installed the ipywidgets extension:

`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

Widgets run on their own within jupyterlab; ipyvolume works with jupyter notebook. However, any call to ipyvolume gives the following error:
**Error displaying widget**

Does anyone know how to make ipyvolume work properly with this setup - particularly in jupyterlab?

**Comment by maartenbreddels** [comment]
Hi Philipp ,

did you run: `jupyter labextension install ipyvolume`?

cheers.

Maarten

**Comment by PhilippBartel** [comment]
Hi Maarten,

I hadn't before posting. Now I have and it works beautifully. Thanks for fixing this for me so quickly!

Is this mentioned anywhere in the documentation? I was looking at the repository readme and the official docs, but found no mention of it. Perhaps I'm missing smth quite obvious here.

Best,
Philipp

**Comment by maartenbreddels** [comment]
I think it does not, and that should be corrected! Thanks for opening this issue.

**Comment by maartenbreddels** [comment]
This is now in the docs and README.md

**Comment by c-amow** [comment]
Hi Maarten,
Shouldn't this minimized example work?
```
import ipyvolume as ipv
import ipyvolume.pylab as p3
import numpy as np
v = np.ones([2,3,4])
ipv.quickvolshow(v) # this run, even though it is meaningless to show
p3.volshow(v)
```
i get:
```
/home/chris/anaconda3/lib/python3.7/site-packages/ipyvolume/serialize.py:77: RuntimeWarning: invalid value encountered in true_divide
  grid_normalized = (grid*1.0 - vmin) / (vmax - vmin)
/home/chris/anaconda3/lib/python3.7/site-packages/ipyvolume/serialize.py:81: RuntimeWarning: invalid value encountered in true_divide
  gradient = gradient / np.sqrt(gradient[0]**2 + gradient[1]**2 + gradient[2]**2)
Error displaying widget
```
I've run (again to make sure - no change)
```
jupyter labextension install ipyvolume
```

if it helps
```
import ipyvolume
ipyvolume.__version__
'0.5.1'
```

It runs without throwing an error in ipython - it just errors out on jupyter

**Comment by maartenbreddels** [comment]
Hi c-amow,

The warning is 'ok', the Error displaying widget is not. Can you check if normal ipywidgets are working?
e.g. `ipywidget.FloatSlider()`

cheers,

Maarten

**Comment by c-amow** [comment]
It was not installed - pip was done, but the `jupyter nbextension enable --py widgetsnbextension` was not
Now the widgets run fine, but I still have the same error I originally reported

**Comment by maartenbreddels** [comment]
> Hi Maarten - wow incredible turnaround time! :)

thx :)

two things, you are using jupyter notebook it seems right? (otherwise the `jupyter nbextension enable --py widgetsnbextension` would not be relevant).
Second, if you had to execute this command, it means you run notebook version < 5.3, which means you also need to run `$ jupyter nbextension enable --py pyvolume`.

Let me know if this works.

PS: please open a new issue next time, but for now lets continue here.

**Comment by c-amow** [comment]
Hi, ok - I was just trying to make sure it wasn't pilot error - I don't mind opening a new one if you want.
Actually I have been using JupyterLab 0.34.9
I just tried in notebook to see if there were any clues about what was going on.

btw, I just did this (not really having any experience debugging jupyterlab):
%debug
> /home/chris/anaconda3/lib/python3.7/site-packages/ipywidgets/widgets/widget.py(662)_handle_msg()
    660         """Called when a msg is received from the front-end"""
    661         data = msg['content']['data']
--> 662         method = data['method']
    663 
    664         if method == 'update':

Which seems useful

**Comment by ptn24** [comment]
Has this issue been patched?

**Comment by maartenbreddels** [comment]
there is not a general issue, i think it was a user or install error. Try creating a new env with the latest jupyter lab and follow the installation instructions.
