### ISSUE TITLE
Text message instead of Plot

### ISSUE THREAD

**Issue by alessandro-zomparelli** [maartenbreddels/ipyvolume#128]
Hi!
I was really interested in this library, but when I try to run the examples I just get a text output:
`VBox(children=(VBox(children=(HBox(children=(Label(value='levels:'), FloatSlider(value=0.25, max=1.0, step=0.0…`

I've seen that this happened before. I'm running it on Ubuntu 16.04 with conda and my browser is Firefox 59.0.2 

Thank you, and compliment for your great job

**Comment by alessandro-zomparelli** [comment]
Same problem with Chrome and Chromium

**Comment by rannbaron** [comment]
I have the same issue! Please help!

**Comment by iluvatar1** [comment]
Same here ... on Mac Os X both firefox and Chrome

**Comment by maartenbreddels** [comment]
I see I never replied to this, sorry, it fell of the radar. Do you run classical notebook or jupyter lab?

**Comment by iluvatar1** [comment]
Hi, well, I kept reading threads and I made it work. On the installation page it reads that for conda you just need to install ipyvolume from conda, but that is not enough, I neded also to enable the  widgets extension for the notebook. Then, after closing everything and openning again (old technique) ipyvolume worked on classical jupyter notebook. So the final instruction (from https://ipyvolume.readthedocs.io/en/latest/install.html, which is different from what the gihut page says)   was:
conda install -c conda-forge ipyvolume
jupyter nbextension enable --py --user ipyvolume
jupyter nbextension enable --py --user widgetsnbextension
Thanks again and great software. It is the first time I am exposed to it and looks really neat.

**Comment by maartenbreddels** [comment]
Thanks, that is a bug in the conda-package: https://github.com/conda-forge/ipyvolume-feedstock/pull/19

**Comment by maartenbreddels** [comment]
Please reopen if it did not fix it.

**Comment by JEGBergqvist** [comment]
On Mac OS X (Mojave) :

ipywebrtc 0.4.1 has requirement ipywidgets>=7.4.0, but you'll have ipywidgets 7.2.1 which is incompatible.

**Comment by JEGBergqvist** [comment]
MacOSX Mojave: Dependencies not automatically correct, needed: pip3 install --upgrade ipywidgets

Due to:
ipywebrtc 0.4.1 has requirement ipywidgets>=7.4.0, but you'll have ipywidgets 7.2.1 which is incompatible.

**Comment by Kata52** [comment]
Hallo, 

I recently started using ipyvolume and find it a great hands-on tool!
Bu now I got a problem:
I am using ipyvolume to visualize a 3d array. I use PhyCharm(2018.4 - Community edition) on Windows 8.1 (64x) and as I run ipv.quickscatter(..) I get the following message, but **no** plot:
VBox(children=(Figure(camera=PerspectiveCamera(fov=46.0, position=(0.0, 0.0, 2.0), quaternion=(0.0, 0.0, 0.0, …
I read the andswer from @iluvatar1 , but I do not know how should I do it with PhyCharm.
If you could help me, how I can enable the widgetsnbextension and the ipyvolume  in my case?
In advance thank you for your answer!

**Comment by Kata52** [comment]
Now I edited it (if it is correct)
```
Enabling notebook extension ipyvolume/extension...
      - Validating: ok
```
```
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok
```
but still get the same message as before without any plot.
