### ISSUE TITLE
anglex and anglez do the same thing?

### ISSUE THREAD

**Issue by mdering** [maartenbreddels/ipyvolume#136]
I've tested this a few times and I can't figure out where but it seems like fig.anglex and fig.anglez do the same thing, neither actually adjusts the z axis. Could you investigate?

**Comment by maartenbreddels** [comment]
In master this is currently different, since I'm not using the threejs camera. I'll keep this open as a reminder to make sure I check everything is working as in version 4 (or better!)

**Comment by maartenbreddels** [comment]
See aad9183c60cdea32f82aa05f8077beee79f83618 for the new API, which is more flexible.
