### ISSUE TITLE
Problems with alpha blending and renderer properties

### ISSUE THREAD

**Issue by OlehKSS** [maartenbreddels/ipyvolume#138]
I am trying to implement alpha blending for two meshes. I am using material property of the mesh class and try to implement custom blending. Color blending seems to work just fine, but if I switch to alpha instead of blending of two meshes I see only the top mesh. Is it possible to implement alpha blending in ipyvolume in this way?

For the [WebGL Renderer](https://threejs.org/docs/#api/renderers/WebGLRenderer) they have an option for enabling transparency buffer, by default it is disabled. Can it be the reason why I don't receive correct alpha? Where can I see or change ipyvolume renderer instance properties?

**Comment by maartenbreddels** [comment]
You could be right, and that would be [here in FigureModel](https://github.com/maartenbreddels/ipyvolume/blob/master/js/src/figure.js#L487).
I think it's good to have this on by default, if you make a PR I'm happy to accept it. Later on we could have it as an option, but I'm ok with this solution for now.

**Comment by OlehKSS** [comment]
Three.js doesn't support alpha channel in colors according to this [pull request](https://github.com/mrdoob/three.js/pull/6898) . So, I will need to try a workaround with `vector4` and a custom shader, as in the [issue](mrdoob/three.js#2730). Could you suggest where I can start to dig in ipyvolume code in order to do that?

**Comment by maartenbreddels** [comment]
Actually, the color array can of shape (M, N, 3 or 4) or (N,3 or 4), where 4 is for rgba values. To be honest, I can remember this not working, please try it out and report back, if you want try out yourself. 
 * https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/ipyvolume/widgets.py#L50 this is where color is defined to be serialized using the color_serialization
 * That refers to https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/ipyvolume/serialize.py#L271 which is using https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/ipyvolume/serialize.py#L245 to convert it to something that goes over the wire.
 * At https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/js/src/mesh.js#L410 you can find that on the front-end we use the color_or_json to convert if from the wire format to something JS friendly
 * And https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/js/src/serialize.js#L290 shows it is using https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/js/src/serialize.js#L139 to do the deserialization.

Hope that helps you understand things and possibly debug it. Feel free to ask more if you don't understand some parts, and you contribution is appreciated!

PS: looking at the code, it seems that only rgb is supported, adding rgba shouldn't be that difficult I hope.

**Comment by larsoner** [comment]
@maartenbreddels looking at the `three.js` issue linked here (the link above is broken) it sounds impossible unless things have changed:

https://github.com/mrdoob/three.js/issues/2730#issuecomment-10992086

Specifically:

> RGBA colors were messier, took more memory and complicated things both from API and implementation point of view.
> ...
> So we went with a route of RGB colors and separate opacity parameter used in materials. This simplified API, made much more predictably behaved materials and saved a third of all color related memory + data transfers.
> ...
> About the only place where occasionally pops-up request for RGBA colors is vertex colors where a solution is to use custom Vector4 attribute instead.

And there is another issue where they again say they are discarded, with a warning:

https://github.com/mrdoob/three.js/issues/6014#issuecomment-123963639

Perhaps I am reading this incorrectly, but it sounds like any alpha component will be discarded at the `three.js` end of things. Thus the potential need for customized shader code passing the colors as a `Vector4`:

> About the only place where occasionally pops-up request for RGBA colors is vertex colors where a solution is to use custom Vector4 attribute instead.

This is a reference to "custom attributes" like this:

https://stackoverflow.com/questions/23280013/custom-attributes-using-threejs

**Comment by maartenbreddels** [comment]
[Ipyvolume has a custom shader for meshes](https://github.com/maartenbreddels/ipyvolume/blob/d43092780ba25cad428dff784accb03c1964edfd/js/glsl/mesh-vertex.glsl#L26) so it would involve moving it to a vec4.
Note that the general issues of transparency (rendering order) isn't solved yet. However, once order independent transparency gets implemented, it isn't much of an issue. And sometimes it doesn't matter that much.

**Comment by OlehKSS** [comment]
[Pull request](https://github.com/maartenbreddels/ipyvolume/pull/139) with draft changes.
