### ISSUE TITLE
npm problem when installing from source (windows)

### ISSUE THREAD

**Issue by mmagnuski** [maartenbreddels/ipyvolume#148]
@maartenbreddels I've followed your advice and installed:
```
conda install -c conda-forge nodejs
```
I still have problems installing from source, where the pip installation claims thatŁ
```
    running egg_info
    running jsdeps
    `npm` unavailable.  If you're running this command using sudo, make sure `npm` is available to sudo
    rebuilding js and css failed
    missing files: ['C:\\proj\\src\\ipyvolume\\ipyvolume\\static\\extension.js', 'C:\\proj\\src\\ipyvolume\\ipyvolume\\static\\index.js', 'C:\\proj\\src\\ipyvolume\\ipyvolume\\static\\three.js']
```
although in the same console session I can do:
```
λ npm --version
5.6.0
```
so npm should be available.
Do you have any ideas on how to better diagnose or fix this problem?

**Comment by maartenbreddels** [comment]
Just letting you know I'm on vacation. Will take a look as soon as I can!

**Comment by maartenbreddels** [comment]
Let me know if the fix works, it seems to install on windows now. Fix comes from https://github.com/jupyter-widgets/widget-cookiecutter/pull/21
