### ISSUE TITLE
Image container

### ISSUE THREAD

**Issue by maartenbreddels** [maartenbreddels/ipyvolume#15]
![animate_a_crop](https://cloud.githubusercontent.com/assets/1765949/23901444/8d4f26f8-08bd-11e7-81e6-cedad0a8471c.gif)

**Comment by GenevieveBuckley** [comment]
![screencast_animation](https://user-images.githubusercontent.com/30920819/46180725-4eda9200-c305-11e8-9d09-4eecae487502.gif)
