### ISSUE TITLE
plot_plane sets zmin, zmax from ylim

### ISSUE THREAD

**Issue by saulthu** [maartenbreddels/ipyvolume#151]
This seems to be getting the incorrect values for the zmin, zmax:

https://github.com/maartenbreddels/ipyvolume/blob/43d98b3e68d6d4b46f9a18b45276ad6590ced48a/ipyvolume/pylab.py#L1035

**Comment by OliverEvans96** [comment]
I'm not the expert, but I think you're right; it looks like a typo to me. Care to submit a PR?

**Comment by maartenbreddels** [comment]
Good catch indeed, Olivier is right, and a PR would be very much appreciated.
