### ISSUE TITLE
Successive calls to savefig in a loop fail to save figure

### ISSUE THREAD

**Issue by glyg** [maartenbreddels/ipyvolume#152]
The following code fails with the error reported bellow. The function `sheet_view` creates two `Mesh` instances and appends them to `ipv.gcf()` with `fig.meshes = fig.meshes + [mesh]` (the code is [here](https://github.com/DamCB/tyssue/blob/master/tyssue/draw/ipv_draw.py#L21)). It works without the call to savfig (and displays the widget twice). 

```python
def view3d(mono):
    ipv.clear()
    # function plotting two meshes
    fig, meshes = sheet_view(mono, mode='3D', **draw_spec)
    ipv.show()
    ipv.savefig('test.png')
    return mesh

for i in range(4):
    view3d(mono)
```

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/py36/lib/python3.6/site-packages/ipyvolume/pylab.py in _screenshot_data(timeout_seconds, output_widget, format, width, height, fig, headless)
    785             with output_widget:
    786                 if timeout and not done[0]:
--> 787                     raise ValueError("timed out, no image data returned")
    788         finally:
    789             with output_widget:

ValueError: timed out, no image data returned

```

Same code but with `exemples.ipv.klein()` works, so maybe I can work around it in my code? Seems related to #109 .

**Comment by glyg** [comment]
Maybe I misdiagnosed the issue, the problem doesn't appear all the time, but seems to be related to the presence/absence of angle modifications via 
```python
fig.anglex = 1.0
fig.angley = 0.2
fig.anglez = 0.1
```
Without those lines in the function body (prior to `ipv.show()`), all seems OK (although the loop displays 4 widgets with my function and only 2 with klein_bottle).

It looks like a problem with the persistence of the widget object?
Sorry I can't be clearer...

**Comment by glyg** [comment]
without changing the function code, successive executions of a notebook cell suffice to trigger (not all the time) the `ValueError: timed out, no image data returned` exception.

**Comment by maartenbreddels** [comment]
Creating screenshots at the moment is a bit of a hack, unfortunately. My recommendation is to make sure the viz is rendered, and in the next cell, call ipv.savefig(...), and continue in the next cell. After savefig the output can be a bit scrambled. My hope/idea is to get better async support in ipywidgets 8, drop Python 2 support and make this go smoother.
Can you try this approach and let me know if that works for you?

**Comment by glyg** [comment]
Calling savefig in the next cell works fine. 

I opened this in case there was a trick to get this to work in a loop. I'll wait for the next releases!

Thanks,
Guillaume
