### ISSUE TITLE
awesome font url broken for ipv.save(offline=true)

### ISSUE THREAD

**Issue by TimoFriedri** [maartenbreddels/ipyvolume#153]
I get the following error:

``` HTTPError: 404 Client Error: Not Found for url: http://fontawesome.io/assets/font-awesome-4.7.0.zip ```

**Comment by maartenbreddels** [comment]
Hi Timo,

that should be fixed in master, by https://github.com/maartenbreddels/ipyvolume/pull/104

cheers,

Maarten
