### ISSUE TITLE
Camera rotation does not work

### ISSUE THREAD

**Issue by OlehKSS** [maartenbreddels/ipyvolume#156]
`ipyvolume.pylab.view` method doesn't work, since `ipyvolume` uses threejs camera now.

**Comment by OlehKSS** [comment]
@maartenbreddels could you share the commit number where you have switched to threejs camera?

**Comment by larsoner** [comment]
@OlehKSS have you tried visually going through the camera code on GitHub with the "blame" mode on? It allows you to see where lines were changed and go back to older commits

**Comment by maartenbreddels** [comment]
Great, you've found it. I must say, the camera changes are quite tricky, every time I fiddle with it I get confused, don't hestitate to ask for help.

**Comment by OlehKSS** [comment]
According to this commit bdd2615 you have removed obsolete camera controls `anglex`, `angley` and `anglez`. We have a bug with `ipyvolume.view`, since these obsolete controls are still used by this function, [see](https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/pylab.py#L908). In order to send rotation angles to JS it is possible to do something like `fig.camera.rotation = (elevation, azimuth, z)`. However, we still need to add some code to update camera position to JS, e. g. [here](https://github.com/maartenbreddels/ipyvolume/blob/master/js/src/figure.js#L529). On JS side you seem to do some camera view changes. I do not quite understand how to combine that code with camera angles update.

**Comment by larsoner** [comment]
I can't remember what the arguments should do, check with PySurfer

You might need to change the "up" direction

Also at some point we want the option to use turntable/terrain style camera control rather than arcball, can you see if it's easy to add that, too, if it's not already there?

**Comment by OlehKSS** [comment]
There is orbit camera control available now in `ipyvolume` with an axis that points up. I guess this is turntable/terrain style camera control. It is possible to switch between trackball and orbit controls using control button above the figure. Trackball is the default setting and it can be changed to orbit. As far as I see, there is no way to change orbit control axis direction now.

**Comment by maartenbreddels** [comment]
Did I merge to early, if so, please indicate with placing 'WIP: ' in front (work in progress). We could take a look at the matlab of mayavi interface to see if it matches that. With my astronomy background, +90 is north pole, -90 is south pole, I think most people find that natural as well.

**Comment by OlehKSS** [comment]
It might be a bit too early... I have found a problem, for some reason I could not affect the default value of  camera orientation. In example, if I build a figure like that and show it:
```python
import ipyvolume as p3

fig = p3.figure(width=500, height=500)
brain = p3.plot_trisurf(rr[:, 0], rr[:, 1], rr[:, 2],
                        triangles=tris, color='grey')
p3.squarelim()
p3.show()
```
Afterwards, in the next cell I do rotation update like that:
```python
p3.view(180, 90)
```
Everything works as expected: I do obtain a mesh, and afterwards I change its orientation.
But if I want to display the figure using orientation different from the default one and do previous steps in one cell:
```python
fig = p3.figure(width=500, height=500)
brain = p3.plot_trisurf(rr[:, 0], rr[:, 1], rr[:, 2],
                        triangles=tris, color='grey')
p3.view(180, 90)
p3.squarelim()
p3.show()
```
It doesn't behave as expected. It doesn't change orientation and uses the default one. I guess it is something with the way traitlets work. Have you faced any kind of this problems before? I am trying to find a way how it can be tackled.

**Comment by fberlinger** [comment]
@OlehKKS

Did you find a way to set the camera rotation? I am able to set the camera to different positions within the simulated environment, however, it is always oriented such that it looks toward the center of the simulated environment (cube). I would love to change that camera orientation such that it is aligned with the direction of a moving particle that I simulate. In other words, I would attached the camera to one of many simulated particles (position) and get this particle's view (orientation) on what's going on.

Thanks for any ideas!
Florian

**Comment by OlehKSS** [comment]
@fberlinger 
I have managed to rotate the camera, see my pull request #158.
I guess you will need to change where camera looks at, but it will require changes in JavaScript, [see](https://github.com/maartenbreddels/ipyvolume/blob/master/js/src/figure.js#L534). In that case I expect it to be quite slow.

**Comment by fberlinger** [comment]
Thanks for your help! Could you provide me with an example on how I could change the camera position and orientation from the jupyter notebook. Let's say I start with a point (x,y,z), which should be the position, and a vector (vx, vy, vz), which should be the orientation, i.e., the direction in which the camera looks.

How could I call a function with these inputs that adjusts the camera? Alternatively, I could also input position and quaternion, which I see in figure.js (`this.camera.position`, `this.camera.quaternion`).

Or would it even just be good enough to comment lines 534 and 1490 in figure.js? Are those overruling quaternion orientations I specify and setting camera to (0,0,0)? Also, `this.camera.lookAt(0, 0, 0);`: is (0,0,0) a point in space at which the cam is looking, or is it the (azimuth, elevation, distance) representation?

Thank you so much, Oleh!
