### ISSUE TITLE
ipyvolume fails to render using jupyter/scipy-notebook & JupyterLab 

### ISSUE THREAD

**Issue by tylere** [maartenbreddels/ipyvolume#161]
Browser console output:
```
Error displaying widget
renderer.js:46 Module ipyvolume, semver range ~0.4.5 is not registered as a widget module
```

![image](https://user-images.githubusercontent.com/92862/43915709-684096d4-9bc0-11e8-98c8-4b3b6a7aa381.png)

Dockerfile:
```
FROM jupyter/scipy-notebook:177037d09156
# https://hub.docker.com/r/jupyter/scipy-notebook/tags/
RUN conda install --yes ipyvolume=0.4.5
RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

<details>
    <summary>docker build output</summary>

    $ docker build -t jupyter-scipy-notebook-ee:test_ipyvolume .
    Sending build context to Docker daemon  41.98kB
    Step 1/3 : FROM jupyter/scipy-notebook:177037d09156
     ---> 07f647bee0ec
    Step 2/3 : RUN conda install --yes ipyvolume=0.4.5
     ---> Using cache
     ---> b192a7dfaf0d
    Step 3/3 : RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
     ---> Running in 3cc292488732
    > /opt/conda/bin/npm pack @jupyter-widgets/jupyterlab-manager
    jupyter-widgets-jupyterlab-manager-0.36.1.tgz
    > node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
    yarn install v1.6.0
    info No lockfile found.
    [1/4] Resolving packages...
    warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    [2/4] Fetching packages...
    info fsevents@1.2.4: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 39.03s.
    > node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
    yarn run v1.6.0
    $ webpack --config webpack.prod.config.js
    Hash: 18b9bef975cb4a696c62
    Version: webpack 4.12.2
    Time: 48960ms
    Built at: 2018-08-09 17:04:03
                                                            Asset       Size  Chunks                    Chunk Names
                             vendors~main.4ae11ca49ef95aaba8cd.js   3.02 MiB       5  [emitted]  [big]  vendors~main
                             674f50d287a8c48dc19ba404d20fe713.eot    162 KiB          [emitted]         
                             912ec66d7572ff821749319396470bde.svg    434 KiB          [emitted]  [big]  
                            fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB          [emitted]         
                             b06871f281fee6b241d60582ae9369b9.ttf    162 KiB          [emitted]         
        vendors~@jupyter-widgets/controls.4cf40f7428c9d075fbf7.js    141 KiB       0  [emitted]         vendors~@jupyter-widgets/controls
                                        1.b6df5f48c55186c86461.js    441 KiB       1  [emitted]  [big]  
                             vendors~vega.8f5323bae2792dc8669f.js    697 KiB       2  [emitted]  [big]  vendors~vega
                                     vega.24f558a784461079beda.js  156 bytes       3  [emitted]         vega
                                        4.6a7d274e81baaaa661e5.js   3.59 KiB       4  [emitted]         
                           af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB          [emitted]         
                                     main.df09bfd74013d66a0b16.js   21.9 KiB       6  [emitted]         main
    vendors~@jupyter-widgets/controls.4cf40f7428c9d075fbf7.js.map    452 KiB       0  [emitted]         vendors~@jupyter-widgets/controls
                                    1.b6df5f48c55186c86461.js.map   1.27 MiB       1  [emitted]         
                         vendors~vega.8f5323bae2792dc8669f.js.map   2.76 MiB       2  [emitted]         vendors~vega
                                 vega.24f558a784461079beda.js.map  105 bytes       3  [emitted]         vega
                                    4.6a7d274e81baaaa661e5.js.map   9.25 KiB       4  [emitted]         
                         vendors~main.4ae11ca49ef95aaba8cd.js.map   10.4 MiB       5  [emitted]         vendors~main
                                 main.df09bfd74013d66a0b16.js.map   80.7 KiB       6  [emitted]         main
                                                       index.html   1.53 KiB          [emitted]         
    Entrypoint main [big] = vendors~main.4ae11ca49ef95aaba8cd.js vendors~main.4ae11ca49ef95aaba8cd.js.map main.df09bfd74013d66a0b16.js main.df09bfd74013d66a0b16.js.map
    [0] readable-stream (ignored) 15 bytes {6} [built]
    [1] crypto (ignored) 15 bytes {6} [optional] [built]
    [2] buffer (ignored) 15 bytes {6} [optional] [built]
    [eTbV] ./node_modules/codemirror/mode sync ^\.\/.*\.js$ 2.78 KiB {4} [built]
    [4] util (ignored) 15 bytes {6} [built]
    [5] vertx (ignored) 15 bytes {6} [optional] [built]
    [6] multi whatwg-fetch ./build/index.out.js 40 bytes {6} [built]
    [7] fs (ignored) 15 bytes {3} [built]
    [8] node-fetch (ignored) 15 bytes {3} [built]
    [ANye] ./build/index.out.js 36.3 KiB {6} [built]
    [J29t] ./node_modules/vega-util/index.js + 36 modules 15.1 KiB {2} [built]
        |    37 modules
    [RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 2.88 KiB {6} [optional] [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {5} [built]
    [etOl] ./node_modules/vega-embed/build/src/embed.js + 913 modules 1.64 MiB {2} [built]
        |    914 modules
    [yLpj] (webpack)/buildin/global.js 489 bytes {5} [built]
        + 1376 hidden modules

    WARNING in vega-lite
      Multiple versions of vega-lite found:
        2.5.1 ./~/vega-lite/build/src from ./~/vega-lite/build/src/index.js
        2.6.0 ./~/vega-lite/build from ./~/vega-lite/build/src/index.js

    Check how you can resolve duplicate packages: 
    https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      912ec66d7572ff821749319396470bde.svg (434 KiB)
      1.b6df5f48c55186c86461.js (441 KiB)
      vendors~vega.8f5323bae2792dc8669f.js (697 KiB)
      vendors~main.4ae11ca49ef95aaba8cd.js (3.02 MiB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (3.04 MiB)
          vendors~main.4ae11ca49ef95aaba8cd.js
          main.df09bfd74013d66a0b16.js

    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
        [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
        [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
        [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
            + 1 hidden module
    Done in 51.26s.
    Removing intermediate container 3cc292488732
     ---> 14ac573f7f62
    Successfully built 14ac573f7f62
    Successfully tagged jupyter-scipy-notebook-ee:test_ipyvolume
    tylere-macbookpro3:jupyter-scipy-notebook-ipyvolume tylere$ docker build -t jupyter-scipy-notebook-ee:test_ipyvolume --no-cache .
    Sending build context to Docker daemon  41.98kB
    Step 1/3 : FROM jupyter/scipy-notebook:177037d09156
     ---> 07f647bee0ec
    Step 2/3 : RUN conda install --yes ipyvolume=0.4.5
     ---> Running in 689661b8c826
    Solving environment: ...working... done

    ==> WARNING: A newer version of conda exists. <==
      current version: 4.5.8
      latest version: 4.5.9

    Please update conda by running

        $ conda update -n base conda

    pyqt-5.6.0           |  5.4 MB | ########## | 100% 
    ipyvolume-0.4.5      |  1.7 MB | ########## | 100% 
    traittypes-0.2.1     |    8 KB | ########## | 100% 
    ipywebrtc-0.3.0      |  368 KB | ########## | 100% 
    qt-5.6.2             | 44.3 MB | ########## | 100% 
    ## Package Plan ##

      environment location: /opt/conda

      added / updated specs: 
        - ipyvolume=0.4.5

    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        pyqt-5.6.0                 |   py36h8210e8a_6         5.4 MB  conda-forge
        ipyvolume-0.4.5            |           py36_0         1.7 MB  conda-forge
        traittypes-0.2.1           |             py_1           8 KB  conda-forge
        ipywebrtc-0.3.0            |             py_1         368 KB  conda-forge
        qt-5.6.2                   |                7        44.3 MB  conda-forge
        ------------------------------------------------------------
                                               Total:        51.8 MB

    The following NEW packages will be INSTALLED:

        ipyvolume:  0.4.5-py36_0         conda-forge
        ipywebrtc:  0.3.0-py_1           conda-forge
        pyqt:       5.6.0-py36h8210e8a_6 conda-forge
        qt:         5.6.2-7              conda-forge
        traittypes: 0.2.1-py_1           conda-forge

    Downloading and Extracting Packages
    Preparing transaction: ...working... done
    Verifying transaction: ...working... done
    Executing transaction: ...working... done

    Removing intermediate container 689661b8c826
     ---> 35a89a4ba86d
    Step 3/3 : RUN jupyter labextension install @jupyter-widgets/jupyterlab-manager
     ---> Running in a4e7634ecc98
    > /opt/conda/bin/npm pack @jupyter-widgets/jupyterlab-manager
    jupyter-widgets-jupyterlab-manager-0.36.1.tgz
    > node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
    yarn install v1.6.0
    info No lockfile found.
    [1/4] Resolving packages...
    warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
    [2/4] Fetching packages...
    info fsevents@1.2.4: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 36.01s.
    > node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
    yarn run v1.6.0
    $ webpack --config webpack.prod.config.js
    Hash: 18b9bef975cb4a696c62
    Version: webpack 4.12.2
    Time: 52957ms
    Built at: 2018-08-09 17:23:28
                                                            Asset       Size  Chunks                    Chunk Names
                             vendors~main.4ae11ca49ef95aaba8cd.js   3.02 MiB       5  [emitted]  [big]  vendors~main
                             674f50d287a8c48dc19ba404d20fe713.eot    162 KiB          [emitted]         
                             912ec66d7572ff821749319396470bde.svg    434 KiB          [emitted]  [big]  
                            fee66e712a8a08eef5805a46892932ad.woff   95.7 KiB          [emitted]         
                             b06871f281fee6b241d60582ae9369b9.ttf    162 KiB          [emitted]         
        vendors~@jupyter-widgets/controls.4cf40f7428c9d075fbf7.js    141 KiB       0  [emitted]         vendors~@jupyter-widgets/controls
                                        1.b6df5f48c55186c86461.js    441 KiB       1  [emitted]  [big]  
                             vendors~vega.8f5323bae2792dc8669f.js    697 KiB       2  [emitted]  [big]  vendors~vega
                                     vega.24f558a784461079beda.js  156 bytes       3  [emitted]         vega
                                        4.6a7d274e81baaaa661e5.js   3.59 KiB       4  [emitted]         
                           af7ae505a9eed503f8b8e6982036873e.woff2   75.4 KiB          [emitted]         
                                     main.df09bfd74013d66a0b16.js   21.9 KiB       6  [emitted]         main
    vendors~@jupyter-widgets/controls.4cf40f7428c9d075fbf7.js.map    452 KiB       0  [emitted]         vendors~@jupyter-widgets/controls
                                    1.b6df5f48c55186c86461.js.map   1.27 MiB       1  [emitted]         
                         vendors~vega.8f5323bae2792dc8669f.js.map   2.76 MiB       2  [emitted]         vendors~vega
                                 vega.24f558a784461079beda.js.map  105 bytes       3  [emitted]         vega
                                    4.6a7d274e81baaaa661e5.js.map   9.25 KiB       4  [emitted]         
                         vendors~main.4ae11ca49ef95aaba8cd.js.map   10.4 MiB       5  [emitted]         vendors~main
                                 main.df09bfd74013d66a0b16.js.map   80.7 KiB       6  [emitted]         main
                                                       index.html   1.53 KiB          [emitted]         
    Entrypoint main [big] = vendors~main.4ae11ca49ef95aaba8cd.js vendors~main.4ae11ca49ef95aaba8cd.js.map main.df09bfd74013d66a0b16.js main.df09bfd74013d66a0b16.js.map
    [0] readable-stream (ignored) 15 bytes {6} [built]
    [1] crypto (ignored) 15 bytes {6} [optional] [built]
    [2] buffer (ignored) 15 bytes {6} [optional] [built]
    [eTbV] ./node_modules/codemirror/mode sync ^\.\/.*\.js$ 2.78 KiB {4} [built]
    [4] util (ignored) 15 bytes {6} [built]
    [5] vertx (ignored) 15 bytes {6} [optional] [built]
    [6] multi whatwg-fetch ./build/index.out.js 40 bytes {6} [built]
    [7] fs (ignored) 15 bytes {3} [built]
    [8] node-fetch (ignored) 15 bytes {3} [built]
    [ANye] ./build/index.out.js 36.3 KiB {6} [built]
    [J29t] ./node_modules/vega-util/index.js + 36 modules 15.1 KiB {2} [built]
        |    37 modules
    [RnhZ] ./node_modules/moment/locale sync ^\.\/.*$ 2.88 KiB {6} [optional] [built]
    [YuTi] (webpack)/buildin/module.js 497 bytes {5} [built]
    [etOl] ./node_modules/vega-embed/build/src/embed.js + 913 modules 1.64 MiB {2} [built]
        |    914 modules
    [yLpj] (webpack)/buildin/global.js 489 bytes {5} [built]
        + 1376 hidden modules

    WARNING in vega-lite
      Multiple versions of vega-lite found:
        2.5.1 ./~/vega-lite/build/src from ./~/vega-lite/build/src/index.js
        2.6.0 ./~/vega-lite/build from ./~/vega-lite/build/src/index.js

    Check how you can resolve duplicate packages: 
    https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

    WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
    This can impact web performance.
    Assets: 
      912ec66d7572ff821749319396470bde.svg (434 KiB)
      1.b6df5f48c55186c86461.js (441 KiB)
      vendors~vega.8f5323bae2792dc8669f.js (697 KiB)
      vendors~main.4ae11ca49ef95aaba8cd.js (3.02 MiB)

    WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
    Entrypoints:
      main (3.04 MiB)
          vendors~main.4ae11ca49ef95aaba8cd.js
          main.df09bfd74013d66a0b16.js

    Child html-webpack-plugin for "index.html":
         1 asset
        Entrypoint undefined = index.html
        [KTNU] ./node_modules/html-loader!./templates/partial.html 567 bytes {0} [built]
        [YuTi] (webpack)/buildin/module.js 497 bytes {0} [built]
        [aS2v] ./node_modules/html-webpack-plugin/lib/loader.js!./templates/template.html 1.22 KiB {0} [built]
        [yLpj] (webpack)/buildin/global.js 489 bytes {0} [built]
            + 1 hidden module
    Done in 55.48s.
    Removing intermediate container a4e7634ecc98
     ---> 14056822d888
    Successfully built 14056822d888
    Successfully tagged jupyter-scipy-notebook-ee:test_ipyvolume
</details>

**Comment by tylere** [comment]
I realize that I may just be installing incorrectly for JupyterLab use, so I opened a docs related issue (#160) as well.

**Comment by maartenbreddels** [comment]
It does work in the classical notebook?

**Comment by tylere** [comment]
Updating the Dockerfile to follow the GitHub [README.md](https://github.com/maartenbreddels/ipyvolume/blob/master/README.md) installation instructions solved the issue.

Updated Dockerfile:
```
FROM jupyter/scipy-notebook:177037d09156
# https://hub.docker.com/r/jupyter/scipy-notebook/tags/
RUN conda install --yes ipyvolume=0.4.5
RUN jupyter labextension install ipyvolume
RUN jupyter labextension install jupyter-threejs
```

**Comment by tylere** [comment]
When I added the ipyvolume package to a [more complex docker image](https://github.com/gee-community/ee-jupyter-contrib/blob/master/docker/jupyter-scipy-notebook-ee/Dockerfile), it caused heap errors during the docker build process (related issue: [jupyterlab/jupyterlab#4824](https://github.com/jupyterlab/jupyterlab/issues/4824)). I was able to avoid this by setting an environment variable:

    export NODE_OPTIONS=--max-old-space-size=16000

**Comment by maartenbreddels** [comment]
Thanks for sharing. This was only for the jupyter build install I guess, since the rest comes from conda.

I noticed that you installed ipyvolume's python package 0.4.5, but the jupyter lab extension 0.4.6. That is ok, but this will leave the classical notebook with a bug that can causes issues with modern chrome browsers. I recommend using 0.4.6 for the conda package as well.

**Comment by tylere** [comment]
Thanks for pointing that out. I have now updated to 0.4.6.

I had chosen v0.4.5 because it was tagged as the "Latest release" on the Github repo's [releases page](https://github.com/maartenbreddels/ipyvolume/releases).

**Comment by marioviti** [comment]
Hello!

wrt I  @maartenbreddels"recommend using 0.4.6 for the conda package as well." 
I get the same issue even if the jupyterlab extension and conda package version match (python 3.8).

```
ipyvolume                 0.4.6                      py_1    conda-forge
```

```
Known labextensions:
   app dir: /home/mviti/miniconda3/envs/jupylab/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        ipyvolume v0.4.6  enabled  OK
        jupyter-matplotlib v0.4.2  enabled  OK
        jupyter-threejs v2.1.1  enabled  OK
```

But when I execute the cell in the jupyterlab 

```
import numpy as np
import ipyvolume as ipv
V = np.zeros((128,128,128)) # our 3d array
# outer box
V[30:-30,30:-30,30:-30] = 0.75
V[35:-35,35:-35,35:-35] = 0.0
# inner box
V[50:-50,50:-50,50:-50] = 0.25
V[55:-55,55:-55,55:-55] = 0.0
ipv.quickvolshow(V, level=[0.25, 0.75], opacity=0.03, level_width=0.1, data_min=0, data_max=1)
```

I get a Loading widget message and this error on the console

```
Error: Module ipyvolume, semver range ~0.4.6 is not registered as a widget module
```
