### ISSUE TITLE
ipyvolume rendering refuses to show after JupyterLab page refresh

### ISSUE THREAD

**Issue by parente** [maartenbreddels/ipyvolume#168]
Hi @maartenbreddels. I ran into the following today when trying ipyvolume for the first time.

JupyterLab 0.34.8, ipywidgets 7.4.1, ipyvolume 0.4.5

1. Create a simple volume rendering
2. Save (or Save Notebook with View State)
3. Refresh the browser page
4. Note volume view does not reappear, gives error about missing model
5. Re-running cell(s) leads to the same error
6. Restarting the kernel and re-running all cells fixes the error

![ipyvolume-jlab-0 34](https://user-images.githubusercontent.com/153745/45309163-15c2b500-b4f1-11e8-8b7e-c587f88a340d.gif)

**Comment by maartenbreddels** [comment]
Dear Peter,

The first is a missing feature for widgets in Jupyter lab, it does not
recreate the widgets at the front-end. At the kernel the figure still
exists and is reused. Try calling `ipv.figure()` to create a new one.

Regards,

Maarten

(from mobile phone)

**Comment by parente** [comment]
Thanks, @maartenbreddels. I didn't know whether this was an ipyvolume issue specifically or something in the widgets. I should have went hunting in the widgets issue tracker first.

**Comment by maartenbreddels** [comment]
No problem, I've been bitten by this myself actually!

**Comment by slabib** [comment]
Hi,
I am a secondary teacher from Melbourne Australia, I just started to learn to teach my y 10 students however i have some issues with creating movie files and I tried everything possible I get this error 
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-69a00da0826b> in <module>()
      2 import IPython.display
      3 import base64
----> 4 with open('wave.gif', 'rb') as gif:
      5     url = b"data:image/gif;base64," +base64.b64encode(gif.read())
      6 IPython.display.Image(url=url.decode('ascii'))

FileNotFoundError: [Errno 2] No such file or directory: 'wave.gif'
Please if you have any suggestions or how can approach this with my students I will appreciated 
Thanks
