### ISSUE TITLE
ipyvolume.embed.embed_html not working for 

### ISSUE THREAD

**Issue by GenevieveBuckley** [maartenbreddels/ipyvolume#175]
I'm having trouble with `embed_html` for ipyvolume 0.5.1

The html file seems to save (and the plain text content looks reasonable, the data should be in there) but when I try to open it in a browser I see a blank screen and get some javascript errors.

I used this code to test the html embedding, like you suggest here https://github.com/maartenbreddels/ipyvolume/issues/118#issuecomment-372821203:
```python
import ipyvolume as ipv
import numpy as np
x, y, z = np.random.rand(3, 100)
fig = ipv.scatter(x, y, z) 
ipv.embed.embed_html('test.html', fig)
```

I have:
* ipyvolume version 0.5.1
* ipywidgets version 7.4.1
* Chrome version 69.0.3497.92 (Official Build) (64-bit)

And these are the errors I'm getting in the Javascript development console:

```
unpkg.com/@jupyter-widgets/html-manager@0.14.4/dist/embed-amd.js:264289 

Download the React DevTools for a better development experience: https://fb.me/react-devtools

You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq

Failed to load resource: net::ERR_FILE_NOT_FOUND ipyvolume.js:1
Failed to load resource: net::ERR_FILE_NOT_FOUND jupyter-threejs.js:1

Falling back to https://unpkg.com/ for ipyvolume@~0.5.1 unpkg.com/@jupyter-widgets/html-manager@0.14.4/dist/embed-amd.js:300581 

Falling back to https://unpkg.com/ for jupyter-threejs@~1.1.0 unpkg.com/@jupyter-widgets/html-manager@0.14.4/dist/embed-amd.js:300581 

Failed to load resource: the server responded with a status of 404 () index.js:1

Refused to execute script from 'https://unpkg.com/ipyvolume@~0.5.1/dist/index.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. test.html:1

Could not instantiate widget unpkg.com/@jupyter-widgets/html-manager@0.14.4/dist/embed-amd.js:40870 

require.min.js:1 Uncaught (in promise) Error: Script error for "ipyvolume"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:1)
    at HTMLScriptElement.onScriptError (require.min.js:1)

require.min.js:1 Uncaught (in promise) Error: Script error for "ipyvolume"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.min.js:1)
    at HTMLScriptElement.onScriptError (require.min.js:1)
```

**Comment by GenevieveBuckley** [comment]
For context, this is with a conda environment using:

```
conda install -c conda-forge ipyvolume
```
which picks up ipyvolume 0.5.1 from conda-forge. And since my jupyter notebook version is > 5.3 I don't think there's anything else I needed to do to enable ipyvolume (but please do let me know if I've misread the README):
```
$ jupyter notebook --version
5.6.0
```

**Comment by vidartf** [comment]
There's an issue with unpk.com: https://unpkg.com/ipyvolume@~0.5.1/dist/index.js

**Comment by GenevieveBuckley** [comment]
Thanks @vidartf! I think we can try to create a workaround that for now.

(For anyone else who happens to have the same problem, here's the link to track progress on the unpk issue: https://github.com/unpkg/unpkg.com/issues/134)

**Comment by GenevieveBuckley** [comment]
Update to add: my workaround is using the development installation (setup instructions are in the README), and the `devmode=True` keyword argument in the `ipv.embed.embed_html()` function.

**Comment by maartenbreddels** [comment]
issue resolved at unpkg
