### ISSUE TITLE
Extension error in Jupyterlab: not registered as a widget module

### ISSUE THREAD

**Issue by hadim** [maartenbreddels/ipyvolume#201]
I am confused about that issue because I tried to downgrade to 0.35.0, 0.35.1 and 0.35.2 and still got the same error. I tried to uninstall/install all my jupyterlab extensions. I also tried to totally remove jupyterlab (including `share/jupyter/lab`) without success.

The error happens yesterday after an update of my conda envs (I can't remember what exactly have been updated but jupyterlab is in the list probably).

Part of the error is:

```
Module jupyter-threejs, semver range ^2.0.2 is not registered as a widget module
```

I also got a similar error with `ipyvolume` instead of `jupyter-threejs` but I can't reproduce it.

Here is a more complete error:

![screenshot from 2018-11-01 09-28-26](https://user-images.githubusercontent.com/528003/47856849-90f06b00-ddbe-11e8-90d5-2cab3fcd556a.png)

```
$ jupyter labextension list
JupyterLab v0.35.3
Known labextensions:
   app dir: /home/hadim/local/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        ipyvolume v0.5.1  enabled  OK
        jupyter-threejs v2.0.2  enabled  OK
```

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/hadim/.condarc
 populated config files : /home/hadim/.condarc
          conda version : 4.5.11
    conda-build version : 3.16.2
         python version : 3.6.6.final.0
       base environment : /home/hadim/local/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/hadim/local/conda/pkgs
                          /home/hadim/.conda/pkgs
       envs directories : /home/hadim/local/conda/envs
                          /home/hadim/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.0 CPython/3.6.6 Linux/4.18.0-10-generic ubuntu/18.10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by hadim** [comment]
If you think it's a JLab issue, let me know and I will open a new one there.

**Comment by vidartf** [comment]
I think this might be an issue of your python packages and JS packages not matching. What do you get for `python -c "import pythreejs._version as v; print(v.__version__)"`?

**Comment by vidartf** [comment]
If your python package version is 1.x, you might have to limit the version of the lab extension, e.g. by `jupyter labextension install jupyter-threejs@1`.

**Comment by hadim** [comment]
In the conda env from where the kernel is:

```
$ python -c "import pythreejs._version as v; print(v.__version__)"
2.0.1
```

Note that the lab extension is installed in my root env.

**Comment by hadim** [comment]
I really don't understand what is going on, it must be something stupid...

The good news is that I have been able to reproduce the issue on binder here: https://mybinder.org/v2/gh/hadim/binder-sandbox/master?urlpath=lab/tree/notebooks/ipyvolume-bug.ipynb

**Comment by hadim** [comment]
Note that the issue does not happen with the notebook client (just switch `lab` to `tree` in the URL).

**Comment by vidartf** [comment]
When I load the repo in Chrome, I get the error `THREE.InstancedBufferAttribute: The constructor now expects normalized as the third argument`. So I'm guessing this is an issue of ipyvolume not being compatible with the 2.0 version of pythreejs? Or rather, with the version of three.js that pythreejs 2.x ships with (r97).

**Comment by vidartf** [comment]
Looking at it closer that is an issue, but I guess not the main issue. I think the main issue is that pythreejs incorrectly reported its version to lab when registering.

**Comment by hadim** [comment]
Switching to 1.1.0 for both the python package and the JS lab extension works for me. So it's probably a regression somewhere in pythreejs.

**Comment by hadim** [comment]
Closing here in favor of https://github.com/jupyter-widgets/pythreejs/issues/230.
