### ISSUE TITLE
Plot polyhedron only from its boundaries

### ISSUE THREAD

**Issue by victortxa** [maartenbreddels/ipyvolume#23]
My doubt is if it would be possible to plot with `ipyvolume` polyhedrons which I have only its boundaries coordinates (x, y and z) and a correspondent property value for its coordinates. 
For example: I have this prism boundaries coordinates and a correspondent property value inside it `x1:1 | x2:2 | y1:3 | y2:4 | z1:5 | z2:6 | density:2670` and another `x1:4 | x2:5 | y1:3 | y2:4 | z1:5 | z2:6 | density:3690`. 
If I understood correctly, I should create a 3d numpy array with a grid that includes both prisms and maybe `NaN` where I don't want to plot any value. Something like figure `a` in this link: http://library.seg.org/action/showFullPopup?id=F1&doi=10.1190%2Ftle33040448.1

PS.: sorry for asking this in the other issue.

**Comment by maartenbreddels** [comment]
Yes, that could work, but I don't know it it would look nice, I think in that situation pythreejs would be more suitable. But you could have the empty regions a low value, and just make that not visible by tweaking the transfer function.

**Comment by victortxa** [comment]
I did this test to verify how it would appear and it was nice, but I will try your suggestion too. 
```from ipyvolume import pylab
data = np.random.randint(0, 2, size=(50,50,50))
data = data.astype('float')
dd[:][:][0:25] = np.nan
pylab.volshow(dd, lighting=True, level=[0.4, 0.6, 0.9])
```
I think the usability of the `ipyvolume` was more interesting to build a quick solution. Do you think this kind of solution fits the comments you made in https://github.com/maartenbreddels/ipyvolume/issues/11 ? I thought about it in the per science module.

**Comment by maartenbreddels** [comment]
I tried this code, it's not fully working, is dd the same as data?. But if you can show me an example, indeed, it could go to a module.

**Comment by victortxa** [comment]
Yes! I modified. Thanks!
