### ISSUE TITLE
Can ipyvolume do a plot that update with real time data?

### ISSUE THREAD

**Issue by lucastan1996** [maartenbreddels/ipyvolume#235]
Hi,

I'll like to illustrate a 3D plot of real time position tracking, where a scatter point represent an object being tracked, so the position of the scatter point will be updated in real time. I know ipyvolume can do animation with preset position, but can it update the plot at real time?
Thanks in advance.

**Comment by lucastan1996** [comment]
I tried to play with this api a little, say an object moving toward x direction:

`import ipyvolume as ipv
import numpy as np
from time import sleep
x,y,z = np.array([[1.], [1],[1]])
ipv.figure()
ipv.xyzlim(0, 10)
display(ipv.gcf())
a=0
while a<10:
    a+=1
    x[0]+=0.5
    ipv.scatter(x,y,z)
    sleep(0.5)`

This is already almost what I want, if only I can remove the previous plotted scatter point. (I just need the last scatter point)
Is there a method to remove the previous point? 
Or maybe clear the whole figure but keep the camera position?

**Comment by lucastan1996** [comment]
After looking through the source code I found that I can clear the scatter points by using Figure.scatters.clear()
Good enough for my purpose, but the code is kinda ugly.(I am new to python) Do you have better suggestion?


import ipyvolume as ipv
import numpy as np
from time import sleep
x,y,z = np.array([[1.], [1],[1]])
a=0
fig = ipv.figure()
ipv.xyzlim(0, 10)
display(ipv.gcf())
#anchor_x,anchor_y,anchor_z = np.array([[0,0,9], [0,0,0],[0,9,0]])
#ipv.scatter(anchor_x,anchor_y,anchor_z)
while a<10:
    a+=1
    x[0]+=0.5
    ipv.scatter(x,y,z)
    sleep(0.5)
    fig.scatters.clear()

**Comment by maartenbreddels** [comment]
Hi,

> ```python
> while a<10:
>     a+=1
>     x[0]+=0.5
> ```

ipyvolume (or Python), cannot know that you've updated the array, usually you need to re-assign it (e.g. `scatter.x = x`), however, you can force it to. e.g.
cell1:
```python
import ipyvolume as ipv
import numpy as np
from time import sleep
x,y,z = np.array([[1.], [1],[1]]) # actually, 1, 1, 1 should work, this is a bug i guess
ipv.figure()
ipv.xyzlim(0, 10)
scatter = ipv.scatter(x,y,z)
ipv.show()
```

cell2:
```
a=0
while a<10:
    a+=1
    x[0]+=0.5
    scatter.send_state('x')
    sleep(0.5)
```

**Comment by lucastan1996** [comment]
Thank you so much, this solved my problem.

**Comment by grajohnt** [comment]
I'm trying to do something similar, but with quiver.

When I implement something like this, I get this original plot, but an equivalent quiver.send_state line throws:
AttributeError: 'NoneType' object has no attribute 'send_state'

From what I can see in the code, quiver returns a scatter object, so I'm not sure why this should be the case?

**Comment by grajohnt** [comment]
Ah, scatter gave the same error. I verified that the code above was working as well.

Rather than updating a single coordinate for a point, I'm trying to add/replace points with each time step, which isn't quite the same thing. I'll keep working on this.
