### ISSUE TITLE
Make Chrome headless location and port configurable 

### ISSUE THREAD

**Issue by razorx89** [maartenbreddels/ipyvolume#238]
Currently, the headless mode uses default parameters from `PyChromeDevTools` for connecting to a chrome headless instance. 
https://github.com/maartenbreddels/ipyvolume/blob/e68b72852b61276f8e6793bc8811f5b2432a155f/ipyvolume/headless.py#L53
However, if you use a chrome headless running as docker instance and want to connect from another docker instance (e.g. when using docker-compose), the headless instance is no longer located at `localhost` or `127.0.0.1`. `ipv.savefig` and `ipv.screenshot` should both accept headless configuration parameters, for instance `headless_kwargs=None` and pass it to the  
`PyChromeDevTools(**(headless_kwargs or {}))`.

**Comment by maartenbreddels** [comment]
That is a very good idea, PR welcome, otherwise, I keep this open as a reminder.

**Comment by alpeshyadav** [comment]
Hey, will you merge this?
@maartenbreddels
