### ISSUE TITLE
Using origins other than (0, 0, 0)?

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#240]
I'm looking for options to show some point cloud with `ipv.quickscatter()`, but find that it will always use (0, 0, 0) as the origin. Is there a way to tell the output widget to show only some specific interval on the three axes? If there is not I'd need to shift the data and might end up with misleading axes values.

**Comment by deeplook** [comment]
Ok, I've discovered `xlim()` and friends...

**Comment by maartenbreddels** [comment]
👍
