### ISSUE TITLE
Rendering multiple datasets in a plot?

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#243]
I wonder how to get multiple datasets rendered inside the same figure? I've tried the following, but that shows only the last one:

```python
import numpy as np
import ipyvolume as ipv

ipv.figure()
x, y, z = np.random.random((3, 1000))
ipv.quickscatter(x, y, z, size=2, color='red', marker="sphere")
x, y, z = np.random.random((3, 1000))
ipv.quickscatter(x, y, z, size=2, color='blue', marker="sphere")
ipv.show()
```

Maybe this a duplicate of #62?

**Comment by GenevieveBuckley** [comment]
`ipv.quickscatter` is actually creating its own `ipv.figure()` inside the convenience function, and adding the scatter points to that new figure object.  Try using `ipv.scatter()` instead:

```python
import numpy as np
import ipyvolume as ipv

ipv.figure()
x, y, z = np.random.random((3, 1000))
ipv.scatter(x, y, z, size=2, color='red', marker="sphere")
x, y, z = np.random.random((3, 1000))
ipv.scatter(x, y, z, size=2, color='blue', marker="sphere")
ipv.show()
```

![ipyvolume](https://user-images.githubusercontent.com/30920819/56259704-59307200-6117-11e9-9869-73157cb2596a.png)

**Comment by deeplook** [comment]
Works great! Thanks!

I had not realized this is the purpose of the `quick` prefix. And while `scatter()` gives a nice docstring, `quickscatter()` doesn't.

**Comment by GenevieveBuckley** [comment]
Good point about the docstrings, do you want to make a pull request? It's not entirely intuitive.

`quickscatter()` and `quickquiver()` could probably have their docstrings modelled after the [quickvolshow docstring](https://github.com/maartenbreddels/ipyvolume/blob/e68b72852b61276f8e6793bc8811f5b2432a155f/ipyvolume/widgets.py#L400) in `ipyvolume/ipyvolume/widgets.py`

**Comment by maartenbreddels** [comment]
quick* is for when you have some data and just want to show it, not deal with any other figure that may or may not already be present. PR welcome!
