### ISSUE TITLE
Möbius strip example

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#249]
I wanted to play more with meshes and triangulations and found the included Klein bottle example to be slightly overwhelming, so I've made one for the Möbius strip, see this gist: https://gist.github.com/deeplook/9c76c4fde7f13c52580ac824e86c5c5e.

So I wouldn't mind contributing this to ipyvolume if it is considered useful. What I'm still struggling though is to make the Möbius strip render texture images like the Klein bottle example does so nicely. If anybody can help with that I'd appreciate very much.

![Screenshot 2019-05-02 at 11 44 14](https://user-images.githubusercontent.com/1001778/57067563-aee84b00-6ccf-11e9-9311-6f4349d0281d.png)

**Comment by GenevieveBuckley** [comment]
Can you link to the textured klein bottle example?

I can't get image textures working with `plot_trisurf()` either. I am able to run the example for image textures with `plot_mesh()` [here](https://github.com/maartenbreddels/ipyvolume/issues/241#issuecomment-486643511). Both `plot_mesh` and `plot_trisurf` rely on the ipyvolume `Mesh` class, so the difference in behaviour is odd. I'm wondering if there is actually a bug here, or if better documentation is needed?

**Comment by deeplook** [comment]
@GenevieveBuckley https://github.com/maartenbreddels/ipyvolume/blob/8deaade77bd3f714cd4026cfc94fb1246f97b0a1/notebooks/demo-0.4.ipynb

**Comment by maartenbreddels** [comment]
Hi,

@deeplook this would be great to put in one of the examples as well. 
@GenevieveBuckley you cannot get that sample code I provided to work, could you open an issue for that?

cheers,

MAarten

**Comment by rpanai** [comment]
Maybe I'm doing something wrong but it seems to me this renders pretty well

```python
def moebius(draw=True, show=True, figure8=False, endpoint=True,
                     uv=True, wireframe=False, texture=None):
    import ipyvolume.pylab as p3
    # http://paulbourke.net/geometry/klein/
    u = np.linspace(0, 2 * pi, num=40, endpoint=endpoint)
    v = np.linspace(-0.4, 0.4, num=40, endpoint=endpoint)
    u, v = np.meshgrid(u, v)
    x = cos(u) + v * cos(u/2) * cos(u)
    y = sin(u) + v * cos(u/2) * sin(u)
    z = v * sin(u/2)
    if draw:
        if texture:
            uv = True
        if uv:
            mesh = p3.plot_mesh(x, y, z, wrapx=not endpoint, wrapy=not endpoint, u=u/(2*np.pi), v=v/(2*np.pi), wireframe=wireframe, texture=texture)
        else:
            mesh = p3.plot_mesh(x, y, z, wrapx=not endpoint, wrapy=not endpoint, wireframe=wireframe, texture=texture)
        if show:
            p3.squarelim()
            p3.show()
        return mesh
    else:
        return x, y, z, u, v
```

**Comment by deeplook** [comment]
@rpanai I'm going to take this code with microscopic changes and create a PR to add it to the existing examples, after having spoken to @maartenbreddels. If you prefer doing it yourself, please let me know...

**Comment by rpanai** [comment]
@deeplook I'd like to do it. Which changes are you suggesting?

**Comment by deeplook** [comment]
It could simply go into `ipyvolume/examples.py`, but @maartenbreddels suggested on gitter to add it to the documentation, too, which would make sense, but it uses `nbsphinx` which I haven't used yet. I guess you could add it to `ipyvolume/examples.py` in a first step, which I hope is ok with @maartenbreddels?

ATM I have something like this, notice the "ö" ;)

```python

from numpy import pi, cos, sin, linspace, meshgrid
import ipyvolume.pylab as p3

def möbius(draw=True, show=True, num=40, endpoint=True,
           uv=True, wireframe=False, texture=None):
    # http://paulbourke.net/geometry/toroidal
    u = linspace(0, 2 * pi, num=num, endpoint=endpoint)
    v = linspace(-0.4, 0.4, num=num, endpoint=endpoint)
    u, v = meshgrid(u, v)
    x = cos(u) + v * cos(u / 2) * cos(u)
    y = sin(u) + v * cos(u / 2) * sin(u)
    z = v * sin(u / 2)
    if draw:
        if texture:
            uv = True
        kwargs = dict(wrapx=not endpoint, wrapy=not endpoint,
                      wireframe=wireframe, texture=texture)
        if uv:
            kwargs.update(dict(u=u/(2*pi), v=v/(2*pi)))
        mesh = p3.plot_mesh(x, y, z, **kwargs)
        if show:
            p3.squarelim()
            p3.show()
        return mesh
    else:
        return x, y, z, u, v
    
mesh = möbius()
```

**Comment by maartenbreddels** [comment]
After https://github.com/maartenbreddels/ipyvolume/pull/299 is in, an example notebook with a screenshot would be nice.

**Comment by rpanai** [comment]
@deeplook I do agree möbius will be nicer but I'm not sure it's a good idea to use accents.

**Comment by deeplook** [comment]
@rpanai  If it's considered an example in the sense that it only illustrates how to use the core, but does not expect anybody to use it as-is, it might be an ok way to help Python 2 die a little faster (oh I see ipyvolume specifies 2.7 explicitly...).

One might argue not enough people have these characters ready on their keybords, but then the name can also be tab-completed in any decent IDE... ;)

**Comment by maartenbreddels** [comment]
I think this example would go better in a notebook, since the code is a bit more visible, I've added some instructions https://ipyvolume.readthedocs.io/en/latest/examples.html how to add an example.
I'll soon add one as well.

**Comment by deeplook** [comment]
@maartenbreddels I agree it's more visible, but at the same time it's also less reusable because it cannot be imported from the code base. If we want that, too, we have to import very clean code (like single functions) inside the notebooks from some example collection, maybe using `%load` cell magics, but could still add additional prose/code.

As an aside I've just created https://github.com/maartenbreddels/ipyvolume/pull/302, where this reuse aspect might not be as dominant. Maybe for the Möbius example that's a bit different, because there's not much to configure for it...

**Comment by deeplook** [comment]
I guess we cab close this, although it would be nice to have a GIF screenshot in the example notebook, too, maybe.

**Comment by maartenbreddels** [comment]
Solved by https://github.com/maartenbreddels/ipyvolume/pull/301 which is included in https://ipyvolume.readthedocs.io/en/latest/examples.html
