### ISSUE TITLE
Sphere texturing

### ISSUE THREAD

**Issue by harkness526** [maartenbreddels/ipyvolume#257]
I'm trying to plot mesh with Earth texture, but as a result, I got a shphere with a strange color. I suppose that problem with u and v, but I don't know how to fix it.
![image](https://user-images.githubusercontent.com/47054623/59114686-623c0380-8950-11e9-9160-0e1de5163dd3.png)

```
import PIL.Image
import numpy as np
import ipyvolume as ipv
image = PIL.Image.open('2k_earth_daymap.jpg')
R = 12742
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)

x = R * np.outer(np.cos(u), np.sin(v))
y = R * np.outer(np.sin(u), np.sin(v))
z = R * np.outer(np.ones(np.size(u)), np.cos(v))

# u = np.array([x/5 +np.sin(k/8*np.pi)*4. for k in range(8)])
# v = np.array([-y/5*(1-k/7.) + z*(k/7.) for k in range(8)])
ipv.figure()
ipv.plot_mesh(x, z, y,u=y, v=x,wireframe=False,texture = image)  #texture = image
# earth.texture = PIL.Image.open('2k_earth_daymap.jpg')
ipv.show() 
```

**Comment by grburgess** [comment]
Is there any progress on this? I'm actually have the same issue.

**Comment by grburgess** [comment]
Here is an example of how to do this @harkness526 

https://github.com/grburgess/gbmgeometry/blob/master/gbmgeometry/geometry/sphere.py#L74

**Comment by maartenbreddels** [comment]
Thanks for the report! I think https://github.com/maartenbreddels/ipyvolume/pull/302 is a good example for this, if not,  please reopen.
