### ISSUE TITLE
Sam

### ISSUE THREAD

**Issue by slabib** [maartenbreddels/ipyvolume#264]
Hi,
I am a secondary teacher from Melbourne Australia, I just started to learn to teach my y 10 students however i have some issues with creating movie files and I tried everything possible I get this error
FileNotFoundError Traceback (most recent call last)
in ()
2 import IPython.display
3 import base64
----> 4 with open('wave.gif', 'rb') as gif:
5 url = b"data:image/gif;base64," +base64.b64encode(gif.read())
6 IPython.display.Image(url=url.decode('ascii'))

FileNotFoundError: [Errno 2] No such file or directory: 'wave.gif'
Please if you have any suggestions or how can approach this with my students I will appreciated
Thanks

**Comment by wolfv** [comment]
the wave.gif file does not exist in the directory you are in. you need to start ipython  or jupyter from the directory where `wave.gif` resides.

**Comment by maartenbreddels** [comment]
I hope that solves your problem, feel free to reopen or comment if not.

**Comment by slabib** [comment]
Thank you,
Can I have access to the wave file so i downloaded into my directory please
Sam


________________________________

**Comment by slabib** [comment]
Thank you,
Can I have access to the wave file so i downloaded into my directory please
Sam
