### ISSUE TITLE
Control of scene lighting?

### ISSUE THREAD

**Issue by noahbenson** [maartenbreddels/ipyvolume#266]
I've been rendering lots of mesh objects using ipyvolume and it's been great; however some of the scenes look fairly dark. I'm trying to figure out how to change this, but so far it's not clear to me what the `lighting` option of the `figure()` function does nor where the lighting data are even stored in the figure objects; is there any guidance available on this topic? Thanks!

**Comment by maartenbreddels** [comment]
Lighting is not really well implemented, you could look at:
https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.widgets.Figure.ambient_coefficient
https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.widgets.Figure.diffuse_coefficient
and change those values.
A better solution would be to depend on pythreejs for this and have full control over lighting.

**Comment by maartenbreddels** [comment]
Note: this is not implemented yet.

**Comment by maartenbreddels** [comment]
Track https://github.com/maartenbreddels/ipyvolume/pull/308 for lighting
