### ISSUE TITLE
Avoid overplotting in movie? / possible pylab.cla or clf

### ISSUE THREAD

**Issue by Severian-desu-ga** [maartenbreddels/ipyvolume#269]
Hi there,
I'm relatively new to python and was interested in testing out your library for rendering
a random walk process with particle interactions. However I noticed that when plotting, a function like  pylab.cla or clf did not exist. Also the online documentation suggested there was none available. 

I am aware that in a previous thread you handled the same topic, however I have been unable to reproduce a significant result using your mentioned workaround. Is there a possible workaround that would work in my case?

The code below is only a snippet of the entire random walk process function where the output, "walk", is the array to be plotted.

     fig = ipv.figure()

     runs = len(walk[0])
     n = #user defined parameter
     size = #user defined parameter
     r = #user defined parameter

     wx = np.zeros([runs,n])
     wy = np.zeros([runs,n])
     wz = np.zeros([runs,n])
                
       for i in range(runs):
            for j in range(n):
                               
                 wx[i,j] = walk[j,i,0]
                 wy[i,j] = walk[j,i,1]
                 wz[i,j] = walk[j,i,2]

     x = np.vstack(wx)
     y = np.vstack(wy)
     z = np.vstack(wz)

     ani = ipv.scatter(x, y, z, marker='sphere', size=r)
     ipv.xyzlim(-size, size)
     ipv.animation_control(ani, interval=200) 
     ipv.show()
                
     bounds = np.zeros([runs])+r
                
     def set_view(figure, framenr, fraction):
                  
          ani = ipv.scatter(x[framenr], y[framenr], z[framenr], marker='sphere', size=r)
          ani.size = bounds
                    
     ipv.movie('wave.gif', set_view, fps=1, frames=runs)

Many thanks!

**Comment by maartenbreddels** [comment]
Because ipyvolume is using widgets, you don't need to call scatter again (and best is you don't). If you do:
```
ani.x = x[framenr]
...
```
it will update it instead.
Also, you should be able to assign the whole array to it, and just change the `sequence_index`.

**Comment by Severian-desu-ga** [comment]
Thank you! Yes, this has drastically simplified my script. You were a great help.

**Comment by maartenbreddels** [comment]
Great, thanks for the reply
