### ISSUE TITLE
Control of camera?

### ISSUE THREAD

**Issue by aba312** [maartenbreddels/ipyvolume#27]
Hi,
Firstly this looks like a lovely, simple, and powerful package. I'm exploring using it instead of MayaVI for large data set 3D visualization and animation in Jupyter Notebook.

I've been looking around in the API for the ability to set the camera view angle or orientation in code. I.e. so that my view always shows up at a specific Elevation and Azimuth angle. 

This is done, for example, in mayavi as `mlab.view(aximuth, elevation)` and in matplotlib (mplot3d)  as `ax.view_init(angle1, angle2)`. 

Is there anything like this in ipyvolume?

Thank you so much, 
~ A

**Comment by maartenbreddels** [comment]
Hi,

thanks for the positive feedback. This code to do this is in master, sth like this should work:
```python
f = p3.figure()
s = p3.scatter(...)
f.angley = np.radians(30)
f.angley = np.radians(45)
```
For the code in master to work, you need ipywidgets 7 (you can install an alpha using `pip install ipywidgets~=7.0.0a2`.
I'll see if I can implement a pylab.view(azimuth, elevation), where the angles are in degrees, that would make it more use friendly.
Hope this helps, let me know if you find issues.

cheers,

Maarten

**Comment by maartenbreddels** [comment]
pylab.view implemented.
