### ISSUE TITLE
Plot does not show up in Chrome Version 76.0.3809.132 (Official Build) (64-bit).

### ISSUE THREAD

**Issue by soerendip** [maartenbreddels/ipyvolume#271]
Rotating the images is a bit tricky. I recommend checking out Pymol. A visualization tool for molecular dynamics. There the mouse interaction is made really great.

**Comment by maartenbreddels** [comment]
Hi,

the title does not seem to match your text. But thanks for the pointer.

cheers,

Maarten

**Comment by maartenbreddels** [comment]
Closing as stale, reopen if neeeded.
