### ISSUE TITLE
Setting animation speed

### ISSUE THREAD

**Issue by mironvanderkolk** [maartenbreddels/ipyvolume#284]
I use ipyvolume to visualize quite large datasets (up to 1e6 scatter glyphs). I use the ipywidgets play widget to animate between timesteps, but I found that I can not set the speed at which the widget updates it's value and the frontend has trouble keeping up. I also tried using Ipyvolumes animation_control widget, but since I used multiple scatters for 1 dataset, I have to create multiple animation controls and they also do not have a setting to adjust the speed.

Do you have any suggestions on how to better do this? I would like the counter to only update after ipyvolume is finished displaying all the glyphs before moving one to the next timestep

**Comment by maartenbreddels** [comment]
Hi,

https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.pylab.animation_control has an interval. In the docs, you can click on the `[source]` link to have a human friendly way of looking at the source. Or go to github to look at the code, where you can find that:
https://github.com/maartenbreddels/ipyvolume/blob/fad27f945f83ead65bd06675aa4c7f08c8979269/ipyvolume/pylab.py#L664
it sets [Figure's animation](https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.widgets.Figure.animation)

I hope this helps.
Tip: use marker="square_2d" for better performance.

cheers,

Maarten

**Comment by mironvanderkolk** [comment]
Thanks for your quick response! Is there any way to link multiple scatters to the same animation control?

**Comment by mironvanderkolk** [comment]
Ah, if this sets the figure animation time, this wouldn't work for me. Ipyvolume automatically interpolates when I set the figure animation time to anything other than zero. Because our data has periodic boundaries, the interpolation does not work for us.

Is there a way to disable this interpolation in the animation?

**Comment by HHKoppelman** [comment]
I believe you can set the interpolation time to zero with  `fig.animation_exponent = 0` 
I hope that works!

**Comment by mironvanderkolk** [comment]
Thanks everybody, I think I got what I needed
