### ISSUE TITLE
Invalid value encountered in true divide

### ISSUE THREAD

**Issue by haegray** [maartenbreddels/ipyvolume#288]
Hello,

I am trying to install this library and having no luck getting a plot to display in my jupyter notebook. I get the same warning as other users have: "RuntimeWarning: invalid value encountered in true_divide gradient = gradient / np.sqrt(gradient[0]**2 + gradient[1]**2 + gradient[2]**2)".

Here's some code snippets I tried to run:

import ipyvolume as ipv   
import numpy as np   
import ipyvolume.pylab as p3
import ipywidgets
V = np.zeros((128,128,128))
V[30:-30,30:-30,30:-30] = 0.75
V[35:-35,35:-35,35:-35] = 0.0
V[50:-50,50:-50,50:-50] = 0.25
V[55:-55,55:-55,55:-55] = 0.0
ipv.quickvolshow(V, level=[0.25, 0.75], opacity=0.03, level_width=0.1, data_min=0, data_max=1)

v = np.ones([2,3,4])
p3.volshow(v)

x, y, z = np.random.random((3, 10000))
ipv.scatter(x, y, z, size=1, marker="sphere")
ipv.show()

I'm not sure what's causing it. I've tried other tips suggested on other posts regarding this issue to no avail. Any advice is appreciated!

`python --version`
Python 3.6.5 :: Anaconda, Inc.

`pip freeze`
alabaster==0.7.10
anaconda-client==1.6.14
anaconda-navigator==1.9.7
anaconda-project==0.8.2
asn1crypto==0.24.0
astroid==1.6.3
astropy==3.0.2
attrs==18.1.0
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
bokeh==0.12.16
boto==2.48.0
Bottleneck==1.2.1
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
colorama==0.3.9
comtypes==1.1.4
conda==4.8.0
conda-build==3.10.5
conda-package-handling==1.6.0
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.7
cycler==0.10.0
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.5
datashape==0.5.4
decorator==4.3.0
distributed==1.21.8
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
gevent==1.3.0
glob2==0.6
greenlet==0.4.13
h5py==2.7.1
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imagesize==1.0.0
ipydatawidgets==4.0.1
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipyvolume==0.4.6
ipywebrtc==0.5.0
ipywidgets==7.4.0
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
llvmlite==0.23.1
locket==0.2.0
lxml==4.2.1
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
menuinst==1.4.14
mistune==0.8.3
mkl-fft==1.0.0
mkl-random==1.0.1
more-itertools==4.1.0
mpmath==1.0.0
msgpack-python==0.5.6
multipledispatch==0.5.0
navigator-updater==0.2.1
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.6.5
numpy==1.14.3
numpydoc==0.8.0
odo==0.5.1
olefile==0.45.1
openpyxl==2.5.3
packaging==17.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.0
partd==0.3.8
path.py==11.0.1
pathlib2==2.3.2
patsy==0.5.0
pep8==1.7.1
pickleshare==0.7.4
Pillow==5.1.0
pkginfo==1.4.2
pluggy==0.6.0
ply==3.11
prompt-toolkit==1.0.15
psutil==5.4.5
py==1.5.3
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.3
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.4
pyodbc==4.0.23
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
pythreejs==2.1.1
pytz==2018.4
PyWavelets==0.5.2
pywin32==223
pywinpty==0.5.1
PyYAML==3.12
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
requests==2.18.4
rope==0.10.7
ruamel-yaml==0.15.35
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.1.0
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.7
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.3
TBB==0.1
tblib==1.3.2
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
torch==1.3.0
torchvision==0.4.1
tornado==5.0.2
tqdm==4.36.1
traitlets==4.3.2
traittypes==0.2.1
typing==3.6.4
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.2
win-inet-pton==1.0.1
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.4
xlwings==0.11.8
xlwt==1.3.0
zict==0.1.3

`jupyter nbextension list`

Known nbextensions:
  config dir: C:\Users\hgray\.jupyter\nbconfig
    notebook section
      ipyvolume/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
  config dir: C:\Users\hgray\AppData\Local\Continuum\anaconda3\etc\jupyter\nbconfig
    notebook section
      ipyvolume/extension enabled
      - Validating: ok
      jupyter-webrtc/extension enabled
      - Validating: ok
      jupyter-datawidgets/extension enabled
      - Validating: ok
      jupyter-threejs/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok

**Comment by omidalam** [comment]
I have the same problem. I tried to update the ipywidgets to the most recent version with no effect.
Any updates on this?

**Comment by maartenbreddels** [comment]
This was just a warning, nothing that should be a problem, fixed in #390
