### ISSUE TITLE
3d Scatter plot of linearly spaced points: data disappear when moving plot

### ISSUE THREAD

**Issue by benmyara** [maartenbreddels/ipyvolume#289]
**Platform**: Jupyter Lab 1.2.0
**ipyvolume version**:  0.5.2

The below code creates linearly spaced points in a cube and plots the 3d points. The plot is correctly drawn, but when I try to rotate it, the data disappear.

```
import ipyvolume as ipv
import numpy as np

num_points = 8
x = np.linspace(start=0, stop=1, num=num_points)
meshgrid = np.meshgrid(x, x, x)
points = np.concatenate([np.expand_dims(e, axis=-1) for e in meshgrid], axis=-1).reshape((-1, 3))
ipv.quickscatter(points[:, 0], points[:, 1], points[:, 2], size=2, marker="sphere")
```

When setting `num_points=7` it works fine.

Note that when using the example from the documentation with points sampled from a Gaussian distribution, I can rotate the plot without any problem.

Original plot:
![image](https://user-images.githubusercontent.com/16196950/71933536-0b7afe80-31ab-11ea-979d-80d7a532e485.png)

When rotating with the mouse:
![image](https://user-images.githubusercontent.com/16196950/71933546-13d33980-31ab-11ea-9871-366a2ed09563.png)

**Comment by maartenbreddels** [comment]
Thanks for opening this, I'l continue in https://github.com/maartenbreddels/ipyvolume/issues/289 as it's a duplicate with a bit more information.
