### ISSUE TITLE
ipyvolume doesn't work with ipywidgets 7

### ISSUE THREAD

**Issue by mwcraig** [maartenbreddels/ipyvolume#30]
This package is awesome, especially being able to embed in static pages!

I don't think this is news, but thought I'd report it. I'm working on a tutorial for scipy on Jupyter widgets and it would be great to include ipyvolume.

**Comment by maartenbreddels** [comment]
Hi Matt,

thanks, I guess you get an error msg in the javascript console. Can you share that with me? And it is news to me, so thanks for letting me know, i think it's awesome!

cheers,

Maarten

**Comment by mwcraig** [comment]
I don't know what changed overnight, but this morning it is working. A couple of errors show up in the javascript console, but the volume render appears. Yesterday it did not....

![ipyvolume-trial_and_re___maartenbreddels_ipyvolume__ipyvolume_doesn_t_work_with_ipywidgets_7___30__-_mattwcraig_gmail_com_-_gmail](https://user-images.githubusercontent.com/1147167/27391631-0934aa0a-566a-11e7-93ac-cbd33ef26174.png)

**Comment by maartenbreddels** [comment]
Oh well, great to see it working. That exception is something I should fix, it doesn't hurt, but it is confusing!
