### ISSUE TITLE
Example plots appearing twice on readthedocs.io

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#303]
Just a heads-up about the very nice Sphinx gallery on https://ipyvolume.readthedocs.io/en/latest/examples.html where I see normal ipyvolume plots shown twice when drilling down into individual examples (tested on Firefox and Safari), like these two, but I'm not enough familiar with that gallery myself, yet:

- https://ipyvolume.readthedocs.io/en/latest/examples/scatter.html
- https://ipyvolume.readthedocs.io/en/latest/examples/mesh.html

**Comment by maartenbreddels** [comment]
Yes, it seems that the jupyter_sphinx plugins injects the javascript into the page no matter what, while nbconvert already did this. I though, 2 is better than 0, but thanks for opening this issue!
That happens somewhere here: https://github.com/jupyter/jupyter-sphinx/blob/master/jupyter_sphinx/__init__.py

A workaround would be to convert all rst files to notebook, and not use that extension anymore.

**Comment by maartenbreddels** [comment]
Related: https://github.com/spatialaudio/nbsphinx/issues/378

**Comment by maartenbreddels** [comment]
We only use nbsphinx now, so solved :)
