### ISSUE TITLE
Control the animation effect speed?

### ISSUE THREAD

**Issue by deeplook** [maartenbreddels/ipyvolume#304]
Is there a way to control the animation effect speed when changing traitlets like in the example below? It appears to take ca. one second now.

```python
import time
import ipyvolume as ipv
import numpy as np

fig = ipv.figure()
x, y, z = np.random.random((3, 100))
s = ipv.scatter(x, y, z, size=5)
ipv.show()

time.sleep(2)
s.x, s.y = s.y, s.x
```

![animation](https://user-images.githubusercontent.com/1001778/78064579-4350a700-7392-11ea-9008-e019ddc6b719.gif)

**Comment by maartenbreddels** [comment]
Yes, try https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.widgets.Figure.animation

**Comment by deeplook** [comment]
Obviously... but thanks, anyway!
