### ISSUE TITLE
getting scatter points coordinate

### ISSUE THREAD

**Issue by prashant905** [maartenbreddels/ipyvolume#318]
Is it possible to get the scatter point coordinates once you click on them?

**Comment by maartenbreddels** [comment]
No, this is not implemented yet. I have ideas on how to do this efficiently though. A separate render pass which each scatter point is rendered with a unique color, and then read off the color. I don't have time for this in the near future, nor is there funding for it. If someone has access to either, I'll be happy to coordinate.

**Comment by maartenbreddels** [comment]
A reply would be polite :)

**Comment by prashant905** [comment]
Sorry for no reply. Since there seems to no quick way around. I have decided to use scatter.selected functionality and pick the max of x and y data among the selected indices. Its a hack but it does the job in a decent manner.

Thanks.

**Comment by maartenbreddels** [comment]
Great idea!, thanks for sharing that, might be helpful for others.

**Comment by maartenbreddels** [comment]
This is implemented in #392 Scatter.clicked_index is the trait you can observe.
