### ISSUE TITLE
Connecting animation control with custom widget/customizing animation control

### ISSUE THREAD

**Issue by luca1308** [maartenbreddels/ipyvolume#332]
Hello, first off: Thanks for this great tool! I am currently trying to animate data for my thesis with ipyvolume and would like to link the values from the animation controls to another widget to output data from a corresponding interactive widget. Is there a way to link the animation control values?

**Comment by kingjr** [comment]
Have you tried manually using widgets with `jslink` and `sequence_index` in your animated object?

**Comment by luca1308** [comment]
> Have you tried manually using widgets with `jslink` and `sequence_index` in your animated object?

I will try later please don't close until I answer
