### ISSUE TITLE
Creating ipyvolume GIF Animation Outside Jupyter

### ISSUE THREAD

**Issue by burakbayramli** [maartenbreddels/ipyvolume#346]

**Comment by maartenbreddels** [comment]
Why was this msg deleted? https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.pylab.savefig can save outside of a Jupyter kernel context.

**Comment by burakbayramli** [comment]
I saw elsewhere you said headless Chrome interfacing was needed.. 

I need to run the script on the command line, stand-alone outside Jupyter.

I tried savefig, I get

```
    ipv.savefig('out.png')
  File "/env3/lib/python3.6/site-packages/ipyvolume/pylab.py", line 901, in savefig
    format=format, width=width, height=height, fig=fig, headless=headless, devmode=devmode))
  File "/env3/lib/python3.6/site-packages/ipyvolume/pylab.py", line 846, in _screenshot_data
    ipython.kernel.do_one_iteration()
AttributeError: 'NoneType' object has no attribute 'kernel'
```
I am on version 0, 5, 2.

**Comment by maartenbreddels** [comment]
Try passing headless=True

**Comment by burakbayramli** [comment]
I have this code


    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9222): Max retries exceeded with url: /json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f16849aedd8>: Failed to establish a new connection: [Errno 111] Connection refused',))
