### ISSUE TITLE
Error displaying widget: model not found for interpret_text.experimental.widget.ExplanationDashboard.ExplanationDashboard

### ISSUE THREAD

**Issue by SharathChandra-AV** [maartenbreddels/ipyvolume#347]
Hello,

This is a dashboard display problem i am facing in JupyterLab from Azure. Please let me know how to fix this.
I am trying to use **InterpretText** on a sample dataset which has text data in a column and a label which tells whether it has some profanity content or not.
Now, when i tried below code.. i see an issue at the last line of the code i.e. ExplanationDashboard****... The moment i run the last line in the below code: 
ExplanationDashboard(local_explanation) 
i get the error 
Error displaying widget: model not found
<interpret_text.experimental.widget.ExplanationDashboard.ExplanationDashboard at 0x7f696c3a9518>

Code:
Iexplainer = ClassicalTextExplainer() 
# fit the data
Iclassifier, best_params = Iexplainer.fit(X_train, Y_train)
print("best classifier: " + str(best_params))
train_accuracy = Iclassifier.score(X_train, Y_train, sample_weight=None)   
print("Train accuracy = " + str(train_accuracy * 100) + "%")
mean_accuracy = Iclassifier.score(X_test, Y_test, sample_weight=None)   
Y_pred = Iclassifier.predict(X_test)
[precision, recall, fscore, support] = precision_recall_fscore_support(Y_test, Y_pred, average='macro')
print("[accuracy, precision, recall, fscore, support] = " + str([(mean_accuracy * 100), precision, recall, fscore, support]))
 Iexplainer.preprocessor.labelEncoder = label_encoder
y = Iclassifier.predict(str(X_test[102]))
local_explanation = Iexplainer.explain_local(str(X_test[102]), y)
# sorted feature importance values and feature names
sorted_local_importance_names = local_explanation.get_ranked_local_names()
sorted_local_importance_values = local_explanation.get_ranked_local_values()
ExplanationDashboard(local_explanation) -------> This is the only line which has problem in displaying dashboard....

**Comment by maartenbreddels** [comment]
I don't think this is ipyvolume related :)
