### ISSUE TITLE
Jupyterlab3 support

### ISSUE THREAD

**Issue by sntgluca** [maartenbreddels/ipyvolume#367]
Hi all,

thanks for the work on ipyvolume! Where 3D visualisation is essential it is hard to avoid using this package :)  
Is there any plan in your roadmap to prepare a package for Jupyterlab3?

**Comment by sandertyu** [comment]
I may have a lead on this. I have an [environment](https://github.com/LibreTexts/widget-testing/tree/all-widgets-jlab3) (repo2docker compatible, you can build the linked repo) with `jupyterlab=3` and `ipyvolume=0.6` that seems to work on all platforms *except* for JupyterLab.

If I launch the linked repository with Binder and make a new notebook, ipyvolume, ipythreejs etc will all work fine, no console errors or anything. Curiously, the labextension list looks like this in the environment;

![labextension-list](https://cdn.discordapp.com/attachments/763198235237154837/829198497902624778/unknown.png)

if you run `jupyter labextension update --all` as recommended then it will install the ipyvolume labextension `0.5.2`. I don't really know what exactly is going on, but I think it would be good if the version of the extension on npm *exactly* matched the version of the ipyvolume that is installed in your environment. @agoose77, this might be something to look at for JupyterLab3 compatibility. I'm not sure if you all are aware that the widget works in some jupyterlab=3 environments, but just not within JupyterLab3 the platform itself.

**Comment by jasongrout** [comment]
Some work on this is over at https://github.com/maartenbreddels/ipyvolume/pull/355

@maartenbreddels, you could do the jlab 3 update in two stages by first just updating the package.json to have the sharedPackages key updated as noted in https://ipywidgets.readthedocs.io/en/stable/changelog.html#updates-for-widget-maintainers. I see you've already updated the `@jupyter-widgets/base` version requirement, so at least part of it is already done. The second stage could be to move to a prebuilt/federated extension.

**Comment by maartenbreddels** [comment]
#355 is merged, and 0.6.0-alpha.8 supports jupyter lab 3.0 🎉 
```pip install ipyvolume==0.6.0a8```
