### ISSUE TITLE
ipv scatter with multiple colors?

### ISSUE THREAD

**Issue by rieder** [maartenbreddels/ipyvolume#375]
It looks like `ipv.scatter` only supports the `color` keyword (for adding a single color to all points), and not the `c` keyword (for adding an individual color to each point, in combination with a cmap). 
Is this indeed the case?
Would it be possible to support an individual color for each point, or would this not be practical in ipv?

**Comment by maartenbreddels** [comment]
Hi Steven!

Yes, multiple colors are supported, see https://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.pylab.scatter
but no colormap support (yet).

cheers,

Maarten

**Comment by maartenbreddels** [comment]
See also https://ipyvolume.readthedocs.io/en/latest/examples/animation.html for some examples.

**Comment by rieder** [comment]
Hi,
Thanks!
So I guess the easiest is just to just map values to colors in advance, and then pass that color array to ipv.scatter?
i.e.
```python
cmap = plt.get_cmap("coolwarm")
c = some_attribute_processed
color = cmap(c)
ipv.scatter(..., color=color)
```

Cheers, Steven

**Comment by rieder** [comment]
(this seems to give exactly the result I wanted)

**Comment by maartenbreddels** [comment]
Great!
