### ISSUE TITLE
Freezing embedded html

### ISSUE THREAD

**Issue by chrisjsewell** [maartenbreddels/ipyvolume#41]
Hey maarten,

As of today, I get an error when trying to view my embedded ipyvolume html files (only if it was created with the dev version):

```
ReferenceError: define is not defined
https://unpkg.com/@jupyter-widgets/html-manager@*/dist/index.js
Line 1
```

Presumably this is caused by the commit of the CombinedCamera define/import?

This was created with the pip ipyvolume (version 0.3) and conda ipywidgets (version 0.6), and still works fine:
https://chrisjsewell.github.io/ipyvolume_si_ech3.html

This was created with my dev ipyvolume (version 0.4 alpha) and pip ipywidgets (version 7.0), and no longer works:
https://chrisjsewell.github.io/3d_atomic/converted/3D%20Atomic%20Visualisation_files/ivol_example1.html

How can I rectify this and is there a way I can 'freeze' the embedded html, such that this won't happen again. I guess I need some .js files locally in the folder?

**Comment by maartenbreddels** [comment]
Hi Chris,

I think https://github.com/jupyter-widgets/ipywidgets/issues/1551 was the issue, I didn't test it yet, but it should be fixed in ipywidget master, not pip yet (i guess you mean 7.0, not 0.7).
The js file for ipyvolume can be (and by default will be) copied to the same folder as the html file. If ipyvolume.js cannot be found, it will be taken from unpkg.com, with the right version number. But I think now the main problem is ipywidgets. I hope I can test that out.

cheers,

Maarten

**Comment by chrisjsewell** [comment]
Ok panic over, in jupyter-widgets/ipywidgets#1556 the following has been changed:

`DEFAULT_EMBED_SCRIPT_URL = u'https://unpkg.com/@jupyter-widgets/html-manager@*/dist/index.js'`

to 

DEFAULT_EMBED_SCRIPT_URL = u'https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed.js'

So the `ipyvolume.embed.embed_html` will technically be faulty unless used with ipywidgets versions after this commit.

**Comment by chrisjsewell** [comment]
But obviously the more general desire remains; to have a static/offline ipyvolume rendering that isn't dependent on (and can't be broken by) any external sources.

**Comment by chrisjsewell** [comment]
Also `ipyvolume.embed.embed_html` doesn't appear to be outputting ipyvolume.js any more. I recall this being fine in version 0.3, has anything changed?

**Comment by maartenbreddels** [comment]
For ipywidgets 6, it will always work since it will get a specific version from unpkg.com. The issue now is that https://github.com/jupyter-widgets/ipywidgets/blob/f354f5e96f94142341b46d0e2d124a08f69bbf39/ipywidgets/embed.py#L45 should not have the * in it (any version), but the version from https://github.com/jupyter-widgets/ipywidgets/blob/f354f5e96f94142341b46d0e2d124a08f69bbf39/ipywidgets/_version.py#L12. Although it may be a bit more complex, since there are now multiple libraries at work. 

(cc @jasongrout) Can you bring this issue up at that repo? I think this should be fixed in ipywidgets7, I think generated snippets should include the proper version number so that it works as long as unpkg.com is up. The alternative is actually to provide your own embed url, like 'embed.js', and put the js in the same directory.

**Comment by maartenbreddels** [comment]
btw, embed_html never did this, but [pylab.save](https://github.com/maartenbreddels/ipyvolume/blob/8218bf1535b2de3e5ce43baa5fa1f11819507dcf/ipyvolume/pylab.py#L568) does.

**Comment by chrisjsewell** [comment]
I could put the embed.js in the same directory, but that also has internal calls to unpkg.com to load require.js, base.js, 'controls.js and index.js. 

What I'm envisioning is an `offline=True` keyword in `embed_html` that will just package all the JS up in a folder, such that I can use the html/js similar to any standard media file, i.e. I can open it offline and have (relative) confidence that any external changes will not break it at a later date.

**Comment by maartenbreddels** [comment]
I fully agree! I think we should move this discussion to ipywidgets, some of it should be fixed for 7.0 I think.

**Comment by jasongrout** [comment]
Let's move the discussion over to ipywidgets, and I'll respond there. @chrisjsewell or @maartenbreddels, can you open an issue?

**Comment by chrisjsewell** [comment]
Oh, one more thing before I forget. The button icons for stereo and fullscreen don't show when I open the embedded html

**Comment by chrisjsewell** [comment]
I see your busy making changes (which look good), so hopefully this will all be fine again soon. But, at the moment every rendering is broke lol:

1. The [readthedocs example](http://ipyvolume.readthedocs.io/en/latest/)
2. My [embedded html example](https://chrisjsewell.github.io/3d_atomic/converted/3D%20Atomic%20Visualisation_files/ivol_example1.html). I tried following the [migration guide](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/migration_guides.md) and simply changing:

```html
<script src="embed.js"></script>
```

to 

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js" integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=" crossorigin="anonymous"></script>

<script>
    window.require(['https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-requirejs'], function(embed) {
        if (document.readyState === "complete") {
            embed.renderWidgets();
        } else {
            window.addEventListener('load', function() {embed.renderWidgets();});
        }
    });
</script>
```

but no success. @jasongrout  I don't know if, after jupyter-widgets/ipywidgets#1615, anything internal to ipyvolume needs to be changed?

3. I tried updating my local fork with the current master, and webpack is now giving me:

```
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'mqtt' in /Users/cjs14/GitHub/ipyvolume/js/src
 @ ./src/index.js 14:22-37

ERROR in ./src/figure.js
Module not found: Error: Cannot resolve module 'screenfull' in /Users/cjs14/GitHub/ipyvolume/js/src
 @ ./src/figure.js 7:13-34

ERROR in ./src/figure.js
Module not found: Error: Cannot resolve module 'style' in /Users/cjs14/GitHub/ipyvolume/js/src
 @ ./src/figure.js 8:0-32
```

Also, I see that you removed the full screen button from the returned container. Are you planning to bring that back at some point?

Ta,
Chris

**Comment by maartenbreddels** [comment]
Can you try again, I've just removed all that (mqtt etc). And the fullscreen button went to a small button in the top left corder. Check master again.

**Comment by chrisjsewell** [comment]
mqtt warning is gone. I had to `npm install screenfull` and so that's fine. But I can't get it to load the style.css, I've tried `npm install style-loader css-loader require-style`  but still no joy.

**Comment by maartenbreddels** [comment]
I think if you run npm install it will download all that is needed (as specified in package.js), does that work?

**Comment by chrisjsewell** [comment]
Ah yes, my bad, forgot about that step. Yep notebook is working again now, and no disappearing meshes. Just need to 

1. work out how to make the embedded html work again. I've just tried saving it again with the master ipyvolume and latest ipywidgets (7.0.0b11), but still not working.
2. get the mesh faces to have a transparency (don't think this is in the code yet is it?), so I can finish my "atomic coordination" figures:

![ivol_example_coordination](https://user-images.githubusercontent.com/2997570/29240921-b886c2f2-7f66-11e7-9139-5130d6099145.png)

**Comment by maartenbreddels** [comment]
Good! How did you get transparency working?!

(from mobile phone)

Op 12 aug. 2017 15:03 schreef "Chris Sewell" <notifications@github.com>:

**Comment by chrisjsewell** [comment]
Oh no I mean they haven't got transparency yet, so I want to write that into ipyvolume. That should be possible shouldn't it?

**Comment by maartenbreddels** [comment]
You'd think so, but it's quite complex actually to do right, especially in combination with volume rendering.

**Comment by chrisjsewell** [comment]
So not as easy as `transparency:true, opacity:0.5` then lol. I guess it requires changes to your custom shaders as well?

**Comment by maartenbreddels** [comment]
It requires a completely new rendering strategy, but I have some ideas in mind requiring multiple passes.

**Comment by chrisjsewell** [comment]
Getting there! The embedded html now loads offline, when there is local; ipyvolume, require and embed files present:

```html
<script src="require.min.js" crossorigin="anonymous"></script>
<script src="embed-amd.js" crossorigin="anonymous"></script>

```
the embed file attempts to load a css font, but it doesn't seem an issue if it can't:

```javascript
exports.push([module.id, "@import url(https://fonts.googleapis.com/css?family=Roboto+Mono);", ""]);

```

The only thing not available is the icons for your new css toolbar.

**Comment by maartenbreddels** [comment]
Great, please report this to ipywidgets, we then may get this fixed for the final release.

**Comment by chrisjsewell** [comment]
Sussed it; I downloaded a local copy of [font awesome](http://fontawesome.io/) and added

```html
    <!-- Font-Awesome CSS -->
    <link href="font-awesome-4.3.0/css/font-awesome.min.css" rel="stylesheet">

```

**Comment by jasongrout** [comment]
That looks like it's from https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/controls/css/labvariables.css#L33, which is just a copy of the JupyterLab file so that we have the appropriate variables. I think we can comment out that line - we don't need it.

**Comment by jasongrout** [comment]
The fontawesome css should be imported by the embed-amd: https://github.com/jupyter-widgets/ipywidgets/blob/master/packages/html-manager/src/libembed.ts#L4. That's weird that it isn't loading.

**Comment by chrisjsewell** [comment]
@jasongrout its loading fine from unpkg.com, just not locally. For example, if I remove https://github.com/chrisjsewell/chrisjsewell.github.io/blob/master/3d_atomic/converted/3D%20Atomic%20Visualisation_files/ivol_example1.html#L11 in my test file and try to open it offline (having cleared my cache), I get:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/2997570/29387887-256fc974-82da-11e7-939e-45e3c64abbd8.png">

or am I doing something wrong?

**Comment by chrisjsewell** [comment]
Oh and @jasongrout I think there is a little typo at https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/embed.py#L60, the url should end .js (although it doesn't seem to matter)

**Comment by jasongrout** [comment]
Right. It used to be a requirejs url, which doesn't have the .js.

**Comment by maartenbreddels** [comment]
@chrisjsewell can we consider this closed?

**Comment by chrisjsewell** [comment]
I believe we can!

**Comment by maartenbreddels** [comment]
👍
