### ISSUE TITLE
Ensure all figure traits are synced when rendering

### ISSUE THREAD

**Issue by chrisjsewell** [maartenbreddels/ipyvolume#42]
Sorry for flooding your issues section lol

So, for instance, setting `fig.anglex = 45` will do nothing if it is before the figure has been displayed.

Adding `this.update_current_control();` to the end of the render function fixes this issue for control traits, but is there a more general method to ensure all traits are synced?

**Comment by maartenbreddels** [comment]
I think that should be the way to do it.
