### ISSUE TITLE
Dissapearing meshes when offset from the origin

### ISSUE THREAD

**Issue by chrisjsewell** [maartenbreddels/ipyvolume#44]
Hey Maarten,

The [triangle meshes example](https://ipyvolume.readthedocs.io/en/latest/mesh.html#Triangle-meshes) works fine. However, when I move the vertices, such that the polygon no longer encapsulates the origin, for example:

```python
p3.plot_trisurf(x+4, y, z, triangles=triangles, color='orange')
```

Then, when rotating the figure, at certain angles the mesh disappears.

![mesh_dissapear](https://user-images.githubusercontent.com/2997570/29004680-7a190cde-7ac3-11e7-8652-3b5904f2b84c.gif)

**Comment by maartenbreddels** [comment]
Ah, thanks for reporting this, I think it's the same bug as here:
https://github.com/maartenbreddels/ipyvolume/commit/0a49fded193b99dd4b865005275f393d438278fb
Do you want to test this out and do a PR? Otherwise I can fix it next week.

**Comment by chrisjsewell** [comment]
Bit above my level of expertise I think (for now lol), so I'll leave that for you :)

**Comment by chrisjsewell** [comment]
FYI, you might want to put in your tutorial that an easy way to compute the triangles is:

```python
from scipy.spatial import ConvexHull
poly = np.array([x,y,z]).T
hull = ConvexHull(poly)
triangles = hull.simplices.tolist()
```

**Comment by maartenbreddels** [comment]
Hey, I cannot reproduce this bug, I think you weren't working from master. I'll see if I can find a place for the convex hull!

**Comment by chrisjsewell** [comment]
OK, once I can get the master working again (see maartenbreddels/ipyvolume#41), I'll give it a go
