### ISSUE TITLE
Embedded HTML failing in Safari (OSX), Explorer (Windows) and all browsers on iOS

### ISSUE THREAD

**Issue by chrisjsewell** [maartenbreddels/ipyvolume#57]
The latest embedded html (including those at http://ipyvolume.readthedocs.io/en/latest/) is failing to load in Safari on OSX and iOS (and Chrome and Firefox on iOS) with the same error:

<img width="1230" alt="image" src="https://user-images.githubusercontent.com/2997570/29497894-ad2dc4f4-85e8-11e7-83b0-55c9fe177a89.png">

These are all fine in http://ipyvolume.readthedocs.io/en/stable/, and Chrome and Firefox are fine on OSX and android.

This is also the case for both the [offline](https://chrisjsewell.github.io/ipyv_test/ipyolume_scatter_offline.html) and [online](https://chrisjsewell.github.io/ipyv_test/ipyolume_scatter_online.html) examples that come from the py.tests.

**Comment by chrisjsewell** [comment]
FYI, I was playing around with [Sauce Labs](https://saucelabs.com/) to test in multiple browsers. For instance, here it is failing in Explorer: https://saucelabs.com/beta/tests/de9061a4351a47b4abf3eb756a431316/watch (~4:00mins)

**Comment by maartenbreddels** [comment]
Also reported [here](https://twitter.com/rasbt/status/902760411577143297) , I think it's time to look into this. I'll check out saucelabs, the included link does not work anymore btw.

**Comment by brickinedifice** [comment]
To folks who still have this issue, can you share whether you are importing ipyvolume in a conda env or in root?

**Comment by maartenbreddels** [comment]
Is this still an issue or can we close this?

**Comment by brickinedifice** [comment]
I couldn't replicate it so from my perspective it makes sense to close it.

**Comment by chrisjsewell** [comment]
bit late to the party, but yes this seems fine now
