### ISSUE TITLE
how to turn off axes?

### ISSUE THREAD

**Issue by choldgraf** [maartenbreddels/ipyvolume#59]
I'm looking for the ipv equivalent of the matplotlib `ax.set_axis_off` method. Sometimes you don't want the box :-)

**Comment by maartenbreddels** [comment]
Indeed, it is possible but badly documented since I haven't really settled on the API yet. 
```python
ipv.style.use('minimal')
# or mix styles using
ipv.style.use(['dark', 'minimal'])
```

**Comment by maartenbreddels** [comment]
Note that since it's a widget, you can play with this in a different cell and see the effect immediately in the current figure.

**Comment by choldgraf** [comment]
I'd be a +1 on a `set_axis_off` method (for matplotlib parity) or something like this to remove the box (maybe even just `fig.box = False`?). Just a thought :-)

**Comment by maartenbreddels** [comment]
Added some helper functions:
```python
ipv.style.background_color('orange')
ipv.style.axes_on()
ipv.style.box_on(
ipv.style.set_style_dark()
```

**Comment by choldgraf** [comment]
🎉 🎉

**Comment by soerendip** [comment]
This is not working. Is there a way to remove the box at all?

```
import ipyvolume as ipv
ipv.style.background_color('orange')
ipv.style.axes_off()
ipv.style.box_off()
ipv.style.set_style_dark()

znorm = Z - Z.min()
znorm /= znorm.ptp() / 100
color = cm.RdYlBu_r(znorm)

ipv.figure()
ipv.plot_wireframe(X, Y, Z, color=color[...,:3])
ipv.show()
```

**Comment by soerendip** [comment]
This works!!

```
import ipyvolume as ipv


znorm = Z - Z.min()
znorm /= znorm.ptp() / 100
color = cm.RdYlBu_r(znorm)

ipv.figure()
ipv.style.axes_off()
ipv.style.box_off()
ipv.plot_wireframe(X, Y, Z, color=color[...,:3])
ipv.show()
```
