### ISSUE TITLE
Scatterplots w/ sprites

### ISSUE THREAD

**Issue by choldgraf** [maartenbreddels/ipyvolume#61]
Is it possible to change scatterplot markers to that they "look" like they're a 2D point (e.g., a flat plane that always faces the camera no matter the orientation).

E.g., this is the default behavior in matlab, so I think a lot of people will have this in mind when they look at the scatter function here:

https://www.mathworks.com/help/matlab/ref/scatter3.html?requestedDomain=www.mathworks.com

**Comment by maartenbreddels** [comment]
Yes, it's been on my TODO list for quite a while, it's called sprites, thanks for opening this. It should also give a better performance for many points, say in the order of 10^6.

**Comment by dakami** [comment]
Please also add opacity support; when plotting large numbers of points being able to alter the blend factors is huge.  (Came here to file that bug, actually.)

**Comment by empeeu** [comment]
I'd be happy to try implementing this if  you can give me a few hints of where to start.

**Comment by maartenbreddels** [comment]
This is implemented, see referred PR's
