### ISSUE TITLE
plotting lines can only be viewed from certain angles

### ISSUE THREAD

**Issue by satra** [maartenbreddels/ipyvolume#64]
view angle A

![image](https://user-images.githubusercontent.com/184063/30089020-e119720e-925e-11e7-8a71-0f4080ed6035.png)

rotated to a different viewing angle

![image](https://user-images.githubusercontent.com/184063/30089023-eb00f1e8-925e-11e7-8a9b-baf7819b3f4a.png)

**Comment by maartenbreddels** [comment]
Thanks for reporting this, probably related to #44, should be easy to fix.

**Comment by satra** [comment]
@maartenbreddels - would this be over here: 

https://github.com/maartenbreddels/ipyvolume/blob/master/js/src/scatter.js#L294

i'm not very comfortable with the code base here.

**Comment by maartenbreddels** [comment]
See the referenced commit for what the issue was, it is more of a workaround until I do all the coordinate transformations the proper threejs way.

**Comment by maartenbreddels** [comment]
I did what you suggested here: https://github.com/maartenbreddels/ipyvolume/commit/c419acdab3e47c056cd37dd6ba58f5c9b12e51c9
but it doesn't disappear anymore. Maybe the browser cache was in play, can you open the notebook in incognito mode, or (for chrome) go to the Developer Tools ->  Network -> Disable Cache

**Comment by satra** [comment]
i tried this and still getting the same outcome.

when trying to do a development install i'm getting the following errors now:

```
 jupyter nbextension install --py --symlink --sys-prefix ipyvolume
Installing /home/neuro/repos/ipyvolume/ipyvolume/static -> ipyvolume
- Validating: problems found:
   X  require: /opt/conda/envs/neuro3/share/jupyter/nbextensions/ipyvolume/extension.js
  OK section: notebook
Full spec: {'section': 'notebook', 'src': 'static', 'dest': 'ipyvolume', 'require': 'ipyvolume/extension'}

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable ipyvolume --py --sys-prefix

neuro@jupyter-satra:~/repos/ipyvolume$ jupyter nbextension enable --py --sys-prefix ipyvolume
Enabling notebook extension ipyvolume/extension...
      - Validating: problems found:
        - require?  X ipyvolume/extension
neuro@jupyter-satra:~/repos/ipyvolume$
```

**Comment by satra** [comment]
i'm going to close this for now - on my os x machine, i just installed everything from scratch and it works with current master. will test inside a docker container next to make sure things are operational.

**Comment by maartenbreddels** [comment]
👍 
browser cache could mess things up as well, try incognito window or (in chrome) open de Dev console, and in the Network tab select 'Disable Cache'.

**Comment by mmagnuski** [comment]
I'm having the same problem on the latest release:
![ipyvolume_lines_disappear](https://user-images.githubusercontent.com/8452354/32106493-20c58122-bb2c-11e7-90af-14b2f1dc65a0.gif)

ipyvolume version: `'0.4.0'`
I wanted to install from master but I get error about `npm` not being present although when I type `npm` in console it works... I'd be thankful for any help :)

**Comment by maartenbreddels** [comment]
Sorry for my late reply, I lost this msg since it was in a closed issue. Indeed, this is not released yet, you need master. Could it be that npm is an alias? If you use anaconda, you can try installing `conda install -c conda-forge nodejs`.

**Comment by mmagnuski** [comment]
Sorry for silence: unfortunatelly the conda install does not help and I'm not sure how to check if `npm` is an alias on windows...
