### ISSUE TITLE
Output a screenshot outside of Jupyter notebook / Headless support

### ISSUE THREAD

**Issue by maartenbreddels** [maartenbreddels/ipyvolume#66]
cc @choldgraf 
ipyvolume is nice for exploring in the notebook, but when doing batch jobs people may want to output screenshots of simulations in a cluster/batch setting, not in a notebook (or at least not in the browser). It would be a shame if just for that you'd have to use another library.
At JupyterCon I've looked at this with @choldgraf and saw this was feasible. The current solution requires you to start chrome headless, and using the `headless=True` argument for savefig it will save the current viz to html, let chrome open that, make a screenshot, and save it to disk.

I'm opening this issue to focus the discussion here.
@choldgraf: would be nice if you could test this and give feedback if it really works in a headless environment.

The documentation is in the [docstring of ipyvolume.headless](https://github.com/maartenbreddels/ipyvolume/blob/master/ipyvolume/headless.py)
after the next release it will also be at readthedocs.

**Comment by choldgraf** [comment]
Hmmm - OK so you need to install `chrome-canary` for now until this features gets incorporated into chrome proper, right?

Also, another quick thought: do you think we could use something like atom as a drop-in for chrome? Maybe that'd be a more lightweight solution? But I'm not sure about the APIs to do this.

**Comment by maartenbreddels** [comment]
You don't need canary, chrome 60 works fine here. I just happen to have it around and prefer to that (i'm not logged into google on canary, so it does affect my history).
I'd say just chrome is pretty light weight already.

**Comment by choldgraf** [comment]
ah ok - the docstring just mentions that you have to use canary, so that confused me. I'll give this a shot as soon as I have some time!

(btw, got lots of people excited about ipyvolume for brain surface viz this week!)

**Comment by maartenbreddels** [comment]
Thanks for the showing this work! Let me know if I can close this (or feel free to close).

**Comment by choldgraf** [comment]
I haven't had time to test this out yet - burning through a bunch of work in prep for a trip to london :-)

**Comment by mdering** [comment]
Is this still the only way to do it? I don't mind if it renders and then saves, I just haven't even gotten that to work yet. Could you talk me through how p3.savefig is supposed to work?

**Comment by maartenbreddels** [comment]
Hi Matt,

it should work, say assuming osx and google canary installed, run this in a shell:
```bash
$ alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
$ chrome-canary --remote-debugging-port=9222 --headless
```
Now you should be able to run:
```python
import ipyvolume as ipv
ipv.examples.klein_bottle()
ipv.view(10,30)
ipv.savefig('headless.png', headless=True)
```
The last command will save the ipywidget state to a html file in a tmp directory, connect to the google canary process, tell it to open that html file, wait a little (for it to render) and then ask to make a screenshot (it will send a base64 encoded png back), then save that to the png file.
Let me know where this fails.

**Comment by maartenbreddels** [comment]
1. No, I should remove the canary reference (fixed). 
2. I think this is the (only?) way to start the remote debugging option, there is no default I think.
3. Yes, that is a bug, just fixed that.

>I can't test it on Mac because I managed to spill coffee on my mac a few months ago :-(

Oh man... 😢

**Comment by choldgraf** [comment]
re: remote debugging, I guess I was asking if having debugging mode on is required for this to work :-)

**Comment by OliverEvans96** [comment]
I'm getting the following error:

```
oliver@oliver-arch:~/python % cat ipyvolume_headless.py 
import ipyvolume as ipv
ipv.examples.klein_bottle()
ipv.view(10,30)
ipv.savefig('headless.png', headless=True)

oliver@oliver-arch:~/python % python ipyvolume_headless.py 
VBox(children=(Figure(camera_center=[0.0, 0.0, 0.0], height=500, matrix_projection=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], matrix_world=[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], meshes=[Mesh(texture=None, triangles=array([[   0,   40,   41],
       [   0,   41,    1],
       [   1,   41,   42],
       ..., 
       [1557, 1598, 1558],
       [1558, 1598, 1599],
       [1558, 1599, 1559]], dtype=uint32), u=array([ 0.        ,  0.02564103,  0.05128205, ...,  0.94871795,
        0.97435897,  1.        ]), v=array([ 0.,  0.,  0., ...,  1.,  1.,  1.]), x=array([ 8.        ,  8.87197017,  9.48814845, ...,  1.78606474,
        2.94639812,  4.        ]), y=array([  0.00000000e+00,   2.89155762e+00,   5.73261761e+00, ...,
        -5.06668790e+00,  -2.56658049e+00,  -3.91886976e-15]), z=array([  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
        -5.15068592e-16,  -4.96202261e-16,  -4.89858720e-16]))], style={'background-color': 'white', 'axes': {'ticklabel': {'color': 'black'}, 'label': {'color': 'black'}, 'color': 'black', 'visible': True}, 'box': {'visible': True}}, tf=None, width=400, xlim=[-19.675974763770302, 16.37529573912293], ylim=[-15.987023970745113, 20.06424653214812], zlim=[-18.025635251446616, 18.025635251446616]),))
Traceback (most recent call last):
  File "ipyvolume_headless.py", line 4, in <module>
    ipv.savefig('headless.png', headless=True)
  File "/home/oliver/python/packages/ipyvolume/ipyvolume/pylab.py", line 864, in savefig
    format=format, width=width, height=height, fig=fig, headless=headless, devmode=devmode))
  File "/home/oliver/python/packages/ipyvolume/ipyvolume/pylab.py", line 820, in _screenshot_data
    data = data[data.find(",") + 1:]
AttributeError: 'NoneType' object has no attribute 'find'
```

Headless chromium is throwing some error, not sure if that's related:

```
oliver@oliver-arch:~/python % chromium --version
Chromium 65.0.3325.162 

oliver@oliver-arch:~/python % chromium --remote-debugging-port=9222 --headless
[0418/143337.501345:ERROR:gpu_process_transport_factory.cc(1019)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:9222/devtools/browser/5b118ee5-d118-43e1-9066-6affeee52018
[0418/143338.436514:ERROR:viz_main_impl.cc(197)] Exiting GPU process due to errors during initialization
[0418/143338.437395:ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /usr/lib/chromium/content_gpu.service
```

**Comment by maartenbreddels** [comment]
I think the issue is in headless chromium for this, the error could be better though!
