### ISSUE TITLE
Controls Not Rendering

### ISSUE THREAD

**Issue by cancan101** [maartenbreddels/ipyvolume#75]
I see the volume rendered but no controls:
![image](https://user-images.githubusercontent.com/51059/31409627-935aed6c-adda-11e7-8028-b74666d45e0c.png)
I have run:
```
jupyter nbextension enable --py --user ipyvolume
jupyter nbextension enable --py --user widgetsnbextension
```
```
$ pip freeze | grep widg
ipywidgets==7.0.1
widgetsnbextension==3.0.3

$ pip freeze | grep jupy
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.3.1
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.0.11
jupyter-latex-envs==1.3.8.4
jupyter-nbextensions-configurator==0.2.7

$ pip freeze | grep note
notebook==5.0.0
```

**Comment by cancan101** [comment]
This seems to fix the issue:
```python
from ipyvolume.widgets import quickvolshow
quickvolshow(...)
```

**Comment by maartenbreddels** [comment]
Ah, actually, I've replaced most controls with the buttons you see on the top left corner. quickvolshow should do the same as volshow actually, I'll open this, since it does seem like inconsistent behaviour.

**Comment by OliverEvans96** [comment]
If by "controls", you mean the sliders which control the transfer function, then I also experience the same thing - quickvolshow generates a VBox with the controls and the figure, while volshow generates only the figure.

**Comment by maartenbreddels** [comment]
Looking back at this, volshow(..) returns the current figure (since there is no difference between the two at the moment). If you want the controls, call ipv.show()
