### ISSUE TITLE
Texture not updating properly

### ISSUE THREAD

**Issue by OliverEvans96** [maartenbreddels/ipyvolume#78]
```
import ipyvolume as ipv
import PIL.Image

f = ipv.figure()
x = linspace(0,1,101)
y = linspace(0,1,101)
X, Y = meshgrid(x,y)
Z = X**2 + Y**2
u = X
v = Y
image = PIL.Image.open("images/WidgetArch.png")
mesh = ipv.plot_mesh(X, Z, Y, u=u, v=v, texture=image, wireframe=False)
ipv.show()
```

renders the mesh with a texture as expected.

```
mesh.u = Y
mesh.v = X
```
ought to flip the image, but has no effect.

```
mesh.u = X
mesh.v = Y
```
then makes the mesh disappear entirely.

Occurred on latest master (98b3314)

**Comment by maartenbreddels** [comment]
`plot_mesh` takes 2d arrays, but they are reshape to be 1d arrays, since `Mesh` expects that. Could you try sth like `mesh.u = mesh.u.reshape(-1)` etc.

**Comment by OliverEvans96** [comment]
Ah. Yep, that's is.

I'm not sure what you're intending `reshape(-1)` to do, but `mesh.u = mesh.u[::-1]` works as expected.
