### ISSUE TITLE
Allow non-square surfaces

### ISSUE THREAD

**Issue by mathieu1** [maartenbreddels/ipyvolume#80]
It would be nice if `plot_surface` would accept arbitrary rectangular matrices X, Y and Z. Currently it seems that `plot_surface` behaves reasonably only when X, Y and Z are square matrices. Indeed, slightly tweaking the [Surface example](http://ipyvolume.readthedocs.io/en/latest/mesh.html#Surfaces)
```python
# f(u, v) -> (u, v, u*v**2)
a = np.arange(-5, 5)
b = np.arange(-10, 10)
U, V = np.meshgrid(a, b)
X = U
Y = V
Z = X*Y**2
p3.figure()
p3.plot_surface(X, Z, Y, color="orange")
p3.plot_wireframe(X, Z, Y, color="black")
p3.show()
```
yields the following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-235-3b8e6be7aa92> in <module>()
      7 Z = X*Y**2
      8 p3.figure()
----> 9 p3.plot_surface(X, Z, Y, color="orange")
     10 p3.plot_wireframe(X, Z, Y, color="black")
     11 p3.show()

~/anaconda/envs/pcp-env/lib/python3.5/site-packages/ipyvolume/pylab.py in plot_surface(x, y, z, color, wrapx, wrapy)
    231     :return: :any:`Mesh`
    232     """
--> 233     return plot_mesh(x, y, z, color=color, wrapx=wrapx, wrapy=wrapy, wireframe=False)
    234 
    235 

~/anaconda/envs/pcp-env/lib/python3.5/site-packages/ipyvolume/pylab.py in plot_mesh(x, y, z, color, wireframe, surface, wrapx, wrapy, u, v, texture)
    343             p3 = index_from2d(i + 1, j + 1)
    344             triangle_index = (i * mx) + j
--> 345             triangles[triangle_index * 2 + 0, :] = [p0, p1, p3]
    346             triangles[triangle_index * 2 + 1, :] = [p0, p3, p2]
    347             lines[triangle_index * 4 + 0, :] = [p0, p1]

IndexError: index 342 is out of bounds for axis 0 with size 342
```
---
If instead we set 
```python
b = np.arange(-3, 3)
```
then no error is thrown but a seemingly incorrect triangulation is produced:
![ipyvolume 2](https://user-images.githubusercontent.com/7703352/31922096-58e618f2-b873-11e7-91cb-dac38929825a.png)

**Comment by maartenbreddels** [comment]
Ok, this should work now, thanks for reporting this!

**Comment by flothesof** [comment]
Hi,
I was bitten by exactly the same problem and opened a bug report that basically states the same thing than the above (here #84). However, it seems this fix has not been uploaded to Pypi and the conda channel (since I installed from there).
Would it be possible to make a new release with commit 5943d6a included?
Thanks in advance,
Florian
