### ISSUE TITLE
RGB volumes

### ISSUE THREAD

**Issue by VolkerH** [maartenbreddels/ipyvolume#81]
Hi,

excuse me if this is a silly question but I've been going through the example notebooks and the documentation and I haven't been able to figure out how to render RGB volumes, e.g. a numpy array of shape [nx, ny, nz, 3] where the last dimensions are RGB values.

If I interpret the examples correctly, most examples seem to plot single-valued volume data and apply some sort of intensity-based RGB lookup table.

**Comment by maartenbreddels** [comment]
Indeed that is usually the case, still, interesting question.
However, do you mean [nx, ny, nz, 3] or [nx, ny, nz, 4], since without an opacity it would always render an opaque cube.

**Comment by VolkerH** [comment]
Actually the data I have is microscopy fluorescence intensity data in multiple channels. I usually want to visualize up to three channels of them simultaneously, typically assigning one of the R,G,B channels to each of them.
The arrays I work with  therefore don't have an explicit opacity channel. That would have to be computed, maybe as the inverse of the total intensity in all channels. The (voxels that don't have fluorescence emission are transparent).

**Comment by GenevieveBuckley** [comment]
Hi @maartenbreddels, I have the same use case as Volker so I'm going to jump in here. 

The kind of microscopy image data we'd be working with would generally arrive as numpy arrays with shape (plane, row, column, channel). Plane, row, and column are the three spatial dimensions (generally called z, y, and x). Channel is represented by color in the image volume. Note that you can have lots of channels - we're not just restricted to 3 for red, green and blue. Alpha is never specified in the data itself, that's something that's part of the particular transfer function you'd apply.

The multivolume rendering https://github.com/maartenbreddels/ipyvolume/pull/143 should make it totally feasible to display this kind of data. We could slice on the channel axis, and plot separate overlapping volumes with a different transfer function for each.

I haven't been able to get the branch with multivolume rendering working yet but if you can help me fix that, I can work on a pull request that does what I've described here.

**Comment by maartenbreddels** [comment]
I think this can now be done using multivolume rendering. Render each channel as a separate volume, and give them 'ramp' transfer function, having a constant color (say red for the first, green for the second), and opacity increasing from 0 to 1.

**Comment by GenevieveBuckley** [comment]
With a bit of fiddling I made this:
![ipyvolume_multivolshow](https://user-images.githubusercontent.com/30920819/46017417-c26c7b80-c11a-11e8-9dba-7f81933bab42.gif)

I'm planning to clean the code up a bit and submit a pull request soon-ish.
