### ISSUE TITLE
examples do not work. No figures shown in notebook. 

### ISSUE THREAD

**Issue by mznyc** [maartenbreddels/ipyvolume#83]
I have installed ipyvolume following the instruction. 

$ pip freeze | grep note
notebook==5.1.0

$ pip freeze | grep widg
autovizwidget==0.12.1
ipywidgets==7.0.3
widgetsnbextension==3.0.3

$ pip freeze | grep jupy
hdijupyterutils==0.12.1
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.1.0
jupyter-contrib-core==0.3.0
jupyter-contrib-nbextensions==0.2.4
jupyter-core==4.3.0
jupyter-highlight-selected-word==0.0.7
jupyter-latex-envs==1.3.7.1
jupyter-nbextensions-configurator==0.2.2
jupyterlab==0.25.2
jupyterlab-launcher==0.3.1
jupyterthemes==0.12.3

## have run widget check script from here(https://raw.githubusercontent.com/mwcraig/scipy2017-jupyter-widgets-tutorial/master/install_check.py):

$ python install_check.py
Checking requirements for Jupyter widget ecosystem
Please install these missing packages for the tutorial "Jupyter widget ecosystem":  (**are these packages necessary?**)
        ccdproc
        bqplot
        ipyleaflet
        ginga
Checking version numbers of these packages:  bqplot, ipyvolume, ipywidgets, ipyleaflet

**** Please upgrade ipywidgets to version 7.0.0a11 by running:
        conda remove --force ipywidgets # if you use conda
        pip install --pre --upgrade ipywidgets
        jupyter nbextension enable --py widgetsnbextension

ipyvolume version is good!

## The  following example only shows sliders, no volume figure  in the notebook. 

import numpy as np
import ipyvolume as ipv
V = np.zeros((128,128,128)) # our 3d array
V[30:-30,30:-30,30:-30] = 0.75
V[35:-35,35:-35,35:-35] = 0.0
V[50:-50,50:-50,50:-50] = 0.25
V[55:-55,55:-55,55:-55] = 0.0
ipv.quickvolshow(V, level=[0.25, 0.75], opacity=0.03, level_width=0.1, data_min=0,data_max=1)

![image](https://user-images.githubusercontent.com/17802524/32616483-7317629c-c540-11e7-8720-3551d1e626df.png)

## The following example does not work and nothing shown in the notebook after this code snippet. 
import ipyvolume as ipv
import numpy as np
x, y, z = np.random.random((3, 10000))
ipv.quickscatter(x, y, z, size=1, marker="sphere")

## Same result as above for the following code.
x, y, z, u, v = ipv.examples.klein_bottle(draw=False)
ipv.figure()
m = ipv.plot_mesh(x, y, z, wireframe=False)
ipv.squarelim()
ipv.show()

##  Only controls shown but no figures after running the following code.

ds = ipv.datasets.aquariusA2.fetch()
ipyvolume.quickvolshow(ds.data, lighting=True)

![image](https://user-images.githubusercontent.com/17802524/32616402-422cb3f8-c540-11e7-9e93-ac77e9919d4a.png)

## My goal is to draw a 3-D scatter plot that can be rotated with a mouse. Is there a good example for this purpose?

**Comment by tlinnet** [comment]
I have the same problem.

The link from the README.md to mybinder.org:
https://beta.mybinder.org/v2/gh/maartenbreddels/ipyvolume/master?filepath=notebooks/simple.ipynb

Shows no graphs.

Looking at '[requirements_rtd.txt](https://github.com/maartenbreddels/ipyvolume/blob/master/requirements_rtd.txt)' in the github folder shows:
```
#jupyter_sphinx>=0.1.1
git+https://github.com/maartenbreddels/jupyter-sphinx@ipywidgets7require_d
ipyvolume==0.4.0
ipywidgets==7.0.0
traittypes
traitlets
Pillow
scipy
nbsphinx
recommonmark
matplotlib<2
ipywebrtc
requests
```

Running: ! pip freeze
in the mybinder, shows:

```
ipyvolume==0.4.0
ipywidgets==7.0.3
traittypes==0.0.6
traitlets==4.3.2
Pillow==4.3.0
scipy==0.19.1
matplotlib==2.1.0
ipywebrtc==0.3.0
requests==2.12.4
```

Is it necessary to downgrade matplotlib to under version 2?

**Comment by maartenbreddels** [comment]
(Sorry for the late reply, been of the radar for a while)
Can you check if this works: http://ipyvolume.readthedocs.io/en/latest/#scatter-plot
If not, your browser could be an issue, if so, can you let me know which browser?
Try chrome otherwise. 
The binder example works for me btw.

**Comment by maartenbreddels** [comment]
requirements_rtd.txt is only for readthedocs btw, which early on gave issues for matplotlib. For binder the [environment.yml)](https://github.com/maartenbreddels/ipyvolume/blob/master/environment.yml) is used.

**Comment by tlinnet** [comment]
Hi.

When I try with Chrome, Version 62.0.3202.94 (Official Build) (64-bit) on Mac: 

And mybinder:
https://beta.mybinder.org/v2/gh/maartenbreddels/ipyvolume/master?filepath=notebooks/simple.ipynb


![screen shot 2017-11-30 at 16 27 24](https://user-images.githubusercontent.com/1208292/33438526-683b64e8-d5eb-11e7-83e0-af5b3ec3e82b.png)

And scatter plot
```
import ipyvolume as ipv
import numpy as np
x, y, z = np.random.random((3, 10000))
ipv.quickscatter(x, y, z, size=1, marker="sphere")
```
![screen shot 2017-11-30 at 16 29 28](https://user-images.githubusercontent.com/1208292/33438630-b4a06c84-d5eb-11e7-9af7-ab44d3c2589c.png)

**Comment by tlinnet** [comment]
On Firefox, 52.5.0 (64-bit) **It works!**

![screen shot 2017-11-30 at 16 30 48](https://user-images.githubusercontent.com/1208292/33438795-14147f66-d5ec-11e7-8feb-523a0648af87.png)

![screen shot 2017-11-30 at 16 32 20](https://user-images.githubusercontent.com/1208292/33438810-1a2075fe-d5ec-11e7-9211-8421437929d3.png)

**Comment by maartenbreddels** [comment]
great, what browser did you use before this?

**Comment by tlinnet** [comment]
Chrome. I will check errors in the developer console.

**Comment by maartenbreddels** [comment]
Interesting, which version and which is?

(from mobile phone)

**Comment by kwinkunks** [comment]
Can't be sure, but I have a similar problem... nothing renders in Chrome v63.0.3239.132 (on macOS), but is fine in Firefox.

![image](https://user-images.githubusercontent.com/1692372/34619042-239bf7ce-f217-11e7-9c7d-bbaf07d9c4ad.png)

**Comment by maartenbreddels** [comment]
Weird, I have tested it on 2 diferrent macbook, and it works fine. Which are you using, or can you tell  me the videocard?

**Comment by maartenbreddels** [comment]
original issue is solved, if the problem persists, please open a new issue.

**Comment by soerendip** [comment]
Plot does not show up in Chrome Version 76.0.3809.132 (Official Build) (64-bit).

**Comment by ShoeGun** [comment]
Plot isn't showing up on Version 77.0.3865.90 (Official Build) (64-bit) MAC either.

**Comment by Michael-H777** [comment]
Plot have no data on Version 78.0.3904.108 (Official Build) (64-bit) windows10. followed all installation instructions for ipyvolume. 
![Annotation 2019-12-04 142157](https://user-images.githubusercontent.com/49025029/70173734-782d4580-16a1-11ea-8e20-d94a3c965043.png)
