### ISSUE TITLE
plot_surface does not produce expected results

### ISSUE THREAD

**Issue by flothesof** [maartenbreddels/ipyvolume#84]
Hi,
thanks for your work on ipyvolume. I've just spent a couple of tens of minutes getting it to work and didn't manage to do it. I'm using a test case from matplotlibs gallery (here: http://matplotlib.org/gallery/mplot3d/surface3d.html#sphx-glr-gallery-mplot3d-surface3d-py).
My first test works.
![image](https://user-images.githubusercontent.com/2360669/33017653-752b7ef4-cdf3-11e7-9a7a-508c1163b576.png)
However, when I'm changing the size of the array X by changing its step size in the arange method, I get weird results.
![image](https://user-images.githubusercontent.com/2360669/33017693-97b35dd4-cdf3-11e7-9334-2d55e7b8f45f.png)
What am I doing wrong?
Here's the source:
```python
# test case 1
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

fig = plt.figure()
ax = fig.gca(projection='3d')

# Make data.
X = np.arange(-5, 5, 0.5)
Y = np.arange(-5, 5, 0.5)
X, Y = np.meshgrid(X, Y, indexing='xy')
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface.
surf = ax.plot_surface(X, Y, Z)

p3.figure()
p3.plot_surface(X, Y, Z)
p3.show()
```

```python
# test case 2
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

fig = plt.figure()
ax = fig.gca(projection='3d')

# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.5)
X, Y = np.meshgrid(X, Y, indexing='xy')
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Plot the surface.
surf = ax.plot_surface(X, Y, Z)

p3.figure()
p3.plot_surface(X, Y, Z)
p3.show()
```
Thanks for your help (this is an amazing project, I'm just sad it didn't work in my case... ^^)

**Comment by maartenbreddels** [comment]
(sorry for the late reply, was off the radar for a while)
Regarding a new version, I'd like to get that out soon, so stay tuned!

**Comment by flothesof** [comment]
Thanks, that would be great. I really appreciate the work you've put into ipyvolume. Best regards. Florian

**Comment by maartenbreddels** [comment]
4.0.1 is release on pypi (conda-forge might take a day)
