### ISSUE TITLE
cannot import name 'version_info'

### ISSUE THREAD

**Issue by StephaneBeauregard** [maartenbreddels/ipyvolume#88]
Deleted.

**Comment by maartenbreddels** [comment]
I messed up the latest release, will fix this asap. Until then you can use
version 4.0.0

(from mobile phone)

**Comment by themmes** [comment]
Why is this issue "deleted"? Ran into the same problem, makes this issue harder to find. @maartenbreddels you mean version `0.4.0`?

For anyone else coming across this issue, make sure you first `pip uninstall` your faulty version of `ipyvolume` and then use; `pip install 'ipyvolume==0.4.0` to install version `0.4.0` as suggested by @maartenbreddels .

**Comment by maartenbreddels** [comment]
@StephaneBeauregard please don't delete issues like this, it can always be useful for other (as you see).

@themmes Yes I meant 0.4.0, but I just released 0.4.2, let me know if that works (pypi only, conda-forge is running..)

**Comment by themmes** [comment]
Brilliant, you're fast! However, I am getting an error on the VBox widget, it is not loading. Can this be due to the update, or is something else wrong? 
I ran both `jupyter nbextension enable --py --sys-prefix widgetsnbextension` and `jupyter nbextension enable --py --sys-prefix ipyvolume`. I restarted my kernel, is it necessary to restart the entire server?

**Comment by maartenbreddels** [comment]
Thx :)
You don't need to restart (pretty sure of that), but you do need to refresh the page. It is sometimes better to just open a notebook so you are sure nothing was left behind.

**Comment by themmes** [comment]
Ah, great, that fixed it!

**Comment by maartenbreddels** [comment]
Great, thanks for letting me know 👍

**Comment by blauwepiet** [comment]
@maartenbreddels The releases go untill 0.4.1 not 0.4.2? Or am I missing something?
The problem is still there in 0.4.1. I just removed the version_info import and it seems to work now but I would like to know if 0.4.2 is already there somewhere.

**Comment by maartenbreddels** [comment]
The issue is only in 0.4.1, and 0.4.2 is out on:
https://pypi.python.org/pypi/ipyvolume shows 0.4.2
and:
https://anaconda.org/conda-forge/ipyvolume
And indeed, that import was the issue.
Where are you installing from?

**Comment by maartenbreddels** [comment]
I noticed I didn't push yet, so my guess is that you were using the git version. I just pushed it (including tags).

**Comment by blauwepiet** [comment]
Yes exactly, I was working with the git version, but thanks for you prompt reply/reaction!

**Comment by maartenbreddels** [comment]
👍
