### ISSUE TITLE
Animated trisurf with variable number of vertices and ipywidgets

### ISSUE THREAD

**Issue by pckroon** [maartenbreddels/ipyvolume#92]
Hello hello,

first off, I like the library, nice work so far! However, I encountered something I want to do, but can't.

I have a timeseries of 3D density data, and I want to make animated contours/isosurfaces/density plots (same concept, different jargon). I make the surfaces with [scikit-image's marching cubes](http://scikit-image.org/docs/dev/api/skimage.measure.html?highlight=isosurface#skimage.measure.marching_cubes_lewiner). And of course I want to plot them with ipyvolume. Plotting a single using `plot_trisurf` works just fine. The trouble comes with animating the whole thing.

The surfaces have a different number of vertices and triangles, so I can't use the build-in animation capabilities. Instead, I elected to do the animation controls with ipywidgets (also because they're shiny).
The first thing I tried was to create all Meshes first, setting their `visible` to `False`, and making the animation loop toggle the correct one. This works for small cases, but uses way to much memory on the JS side to work for my case. 
The next attempt was to create the appropriate Mesh on change, but I haven't found a way to remove the previous Mesh (and after drawing 10 on top of each other my memory craps out).

So, my questions: is there a convenient way to 1) animate trisurf's with different numbers of vertices (#90); or 2) remove specific Meshes from the figure; or 3) clear all meshes from the figure without modifying the scene limits or the camera?

Keep up the good work, ipyvolume is one of the three 3D plotting libraries I found with a quick search (next to Mayavi (pain to install/doesn't work on Py3) and Plot.ly)! And I like yours better so far :)

PS. Maybe good to add, I also tried setting the Mesh's `.x`, `.y`, `.z` and `.triangles` attributes, but that didn't propagate to the picture.

**Comment by maartenbreddels** [comment]
Hi Peter,

thanks for your positive words! 
Note that there is a (ipyvolume.plot_isosurface)[http://ipyvolume.readthedocs.io/en/latest/api.html#ipyvolume.pylab.plot_isosurface] function, but it does exactly what you do with skimage. 
Indeed it is related to #90, and a good example of why some interpolation is needed.
The memory usage is indeed the reason why I did the interpolation for the Scatter object, for the Mesh, there is still some work to be done.
To remove all meshes, you can do:
```python
fig = ipv.gcf()
meshes = list(fig.meshes) # not sure what happens when you close before removing
fig.meshes = []
for mesh in meshes:
 mesh.close()
```
To remove a specific mesh:
```python
fig = ipv.gcf()
meshes = list(fig.meshes) # make a copy, otherwise we modify in place, which traitlets won't detect
meshes.remove(some_mesh)
fig.meshes = meshes
```
I'll continue the discussion in #90 for the interpolation, please subscribe to that if you want to follow up.

Could you open a new issue for the issue in the PS?

**Comment by pckroon** [comment]
Hi,

thanks for the quick reply. Unfortunately I'm not near my computer with either ipyvolume or my data, so I can't try things yet. 
I'll give things a whirl, make a minimal example for the PS, and try to get back to you the second week of January.

Happy holidays :)

**Comment by pckroon** [comment]
Hello hello,

Back from holidays :)
I got my simulation to work (code below), so that's good. However, as it progresses I notice Chrome eating more and more memory. 100 frames works comfortably, but 200 becomes tricky (I have 200 at the moment). I ran it through the profiler in the dev tools, and it appears the memory is dissapearing into the JS heap. I also tried adding `old.close()` at the end, but that didn't help.

```python
# fiber_surfs and ring_surfs are lists of surfaces as made by 
# skimage.measure.marching_cubes_lewiner

fig = ipv.figure(width=600, height=600)
fib_surf = fiber_surfs[0]

ipv.plot_trisurf(fib_surf[0][:, 0], fib_surf[0][:, 1], fib_surf[0][:, 2], fib_surf[1])
ring_surf = ring_surfs[0]

ring_mesh = ipv.plot_trisurf(ring_surf[0][:, 0], ring_surf[0][:, 1], ring_surf[0][:, 2], ring_surf[1], color=(0, 0, 1))

def make_visible(change):
    global ring_mesh
    fig = ipv.gcf()
    old = ring_mesh
    target = change['new']
    ring_surf = ring_surfs[target]
    # Draw the new mesh before removing the old prevents flashing/stuttering
    ring_mesh = ipv.plot_trisurf(ring_surf[0][:, 0], ring_surf[0][:, 1], ring_surf[0][:, 2], triangles=ring_surf[1], color='blue')
    meshes = list(fig.meshes)
    meshes.remove(old)
    fig.meshes = meshes 


slider = ipywidgets.IntSlider(min=0, max=len(ring_surfs)-1, step=1, value=0)
slider.observe(make_visible, 'value', 'change')

play_button = ipywidgets.Play(min=0, max=len(ring_surfs)-1, interval=200)
ipywidgets.jslink((play_button, 'value'), (slider, 'value'))
ipywidgets.HBox([play_button, slider])

fig
```

**Comment by maartenbreddels** [comment]
I think this is solved (see referenced PR), if not open again please.

**Comment by maartenbreddels** [comment]
Great, thanks for the feedback
