### ISSUE TITLE
Changing mesh's x, y, and z does not propagate to figure

### ISSUE THREAD

**Issue by pckroon** [maartenbreddels/ipyvolume#95]
Hello,

As discussed in #92 a separate issue. If I change a mesh's x, y and z attributes it's not propagated to the image.

```python
import numpy as np
import ipyvolume.pylab as ipv
verts = np.array([[0,0,0], [1,0,0],[0.5, np.sqrt(3/4), 0], [0.5, 0.4, 0.6]])
triangs = np.array([[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]], dtype=int)

ipv.plot_trisurf(verts[:, 0], verts[:, 1], verts[:, 2], triangs)
ipv.show()

new_verts = verts.copy()
new_verts[-1, 1] += 1
fig = ipv.gcf()
mesh = fig.meshes[0]
mesh.x = new_verts[:, 0]
mesh.y = new_verts[:, 1]
mesh.z = new_verts[:, 2]
```

**Comment by maartenbreddels** [comment]
I cannot reproduce this. Make sure you call ipv.figure() before you run it again to produce a new image. Which version are you using, from github?

**Comment by pckroon** [comment]
Hi,

I'm running 0.4.2, but it seems to have fixed itself in the meantime...
Thanks for having a look though.

**Comment by maartenbreddels** [comment]
good, thanks for closing this!
